; generated by Slic3r 0.9.6-dev on 2012-11-20 at 10:06:48

; This config has a workaround for the extrusion retraction compensation bug for the first layer... be sure to comment out those 3 lines IF the bug has been fixed.

; layer_height = .1
; perimeters = 1
; top_solid_layers = 0
; bottom_solid_layers = 0
; fill_density = 0
; perimeter_speed = 100
; infill_speed = 100
; travel_speed = 100
; scale = 1
; nozzle_diameter = .345
; filament_diameter = 3
; extrusion_multiplier = 1
; perimeters extrusion width = 0.48mm
; infill extrusion width = 0.48mm
; first layer extrusion width = 0.48mm

G92 E0
G1 E100
G1 E0
G90 ; use absolute coordinates
G21 ; set units to millimeters
G92 E0 ; reset extrusion distance
M82 ; use absolute distances for extrusion
G1 Z0.100 F6000.000 ; move to next layer (0)
G1 X84.175 Y88.992 ; move to first perimeter point
G1 X115.831 Y88.992 F6000.000 E0.20670 ; perimeter
G1 X100.143 Y111.054 E0.38346 ; perimeter
G1 X84.215 Y89.048 E0.56084 ; perimeter
G1 X84.175 Y88.992 E0.56129 ; perimeter
G1 Z0.200 F6000.000 ; move to next layer (1)
G1 X84.175 Y88.992 ; move to first perimeter point
G1 X115.831 Y88.992 F6000.000 E0.76799 ; perimeter
G1 X100.130 Y111.073 E0.94490 ; perimeter
G1 X96.256 Y105.725 E0.98801 ; perimeter
G1 X96.130 Y105.495 E0.98972 ; perimeter
G1 X84.215 Y89.048 E1.12233 ; perimeter
G1 X84.175 Y88.992 E1.12279 ; perimeter
G1 Z0.300 F6000.000 ; move to next layer (2)
G1 X84.175 Y88.992 ; move to first perimeter point
G1 X115.831 Y88.992 F6000.000 E1.32948 ; perimeter
G1 X100.366 Y110.741 E1.50373 ; perimeter
G1 X100.152 Y111.140 E1.50669 ; perimeter
G1 X96.340 Y105.877 E1.54912 ; perimeter
G1 X96.130 Y105.495 E1.55196 ; perimeter
G1 X84.215 Y89.048 E1.68458 ; perimeter
G1 X84.175 Y88.992 E1.68503 ; perimeter
G1 Z0.400 F6000.000 ; move to next layer (3)
G1 X84.175 Y88.992 ; move to first perimeter point
G1 X115.831 Y88.992 F6000.000 E1.89173 ; perimeter
G1 X100.474 Y110.588 E2.06475 ; perimeter
G1 X100.156 Y111.182 E2.06915 ; perimeter
G1 X96.424 Y106.030 E2.11069 ; perimeter
G1 X96.130 Y105.495 E2.11467 ; perimeter
G1 X84.215 Y89.048 E2.24729 ; perimeter
G1 X84.175 Y88.992 E2.24774 ; perimeter
G1 Z0.500 F6000.000 ; move to next layer (4)
G1 X84.175 Y88.992 ; move to first perimeter point
G1 X115.831 Y88.992 F6000.000 E2.45444 ; perimeter
G1 X100.583 Y110.435 E2.62624 ; perimeter
G1 X100.275 Y111.009 E2.63049 ; perimeter
G1 X100.003 Y111.009 E2.63226 ; perimeter
G1 X96.508 Y106.183 E2.67117 ; perimeter
G1 X96.130 Y105.495 E2.67629 ; perimeter
G1 X84.215 Y89.048 E2.80891 ; perimeter
G1 X84.175 Y88.992 E2.80936 ; perimeter
G1 Z0.600 F6000.000 ; move to next layer (5)
G1 X84.175 Y88.992 ; move to first perimeter point
G1 X115.831 Y88.992 F6000.000 E3.01605 ; perimeter
G1 X100.692 Y110.283 E3.18663 ; perimeter
G1 X100.302 Y111.009 E3.19201 ; perimeter
G1 X99.977 Y111.009 E3.19414 ; perimeter
G1 X96.592 Y106.335 E3.23181 ; perimeter
G1 X96.130 Y105.495 E3.23807 ; perimeter
G1 X84.215 Y89.048 E3.37069 ; perimeter
G1 X84.175 Y88.992 E3.37114 ; perimeter
G1 Z0.700 F6000.000 ; move to next layer (6)
G1 X84.175 Y88.992 ; move to first perimeter point
G1 X115.831 Y88.992 F6000.000 E3.57783 ; perimeter
G1 X100.800 Y110.130 E3.74719 ; perimeter
G1 X100.329 Y111.009 E3.75370 ; perimeter
G1 X99.950 Y111.009 E3.75617 ; perimeter
G1 X96.676 Y106.488 E3.79262 ; perimeter
G1 X96.130 Y105.495 E3.80002 ; perimeter
G1 X84.215 Y89.048 E3.93263 ; perimeter
G1 X84.175 Y88.992 E3.93308 ; perimeter
G1 Z0.800 F6000.000 ; move to next layer (7)
G1 X84.175 Y88.992 ; move to first perimeter point
G1 X115.831 Y88.992 F6000.000 E4.13978 ; perimeter
G1 X100.909 Y109.977 E4.30791 ; perimeter
G1 X100.355 Y111.009 E4.31555 ; perimeter
G1 X99.923 Y111.009 E4.31837 ; perimeter
G1 X96.760 Y106.641 E4.35359 ; perimeter
G1 X96.130 Y105.495 E4.36212 ; perimeter
G1 X84.215 Y89.048 E4.49474 ; perimeter
G1 X84.175 Y88.992 E4.49519 ; perimeter
G1 Z0.900 F6000.000 ; move to next layer (8)
G1 X84.175 Y88.992 ; move to first perimeter point
G1 X115.831 Y88.992 F6000.000 E4.70188 ; perimeter
G1 X101.017 Y109.824 E4.86879 ; perimeter
G1 X100.382 Y111.009 E4.87757 ; perimeter
G1 X99.897 Y111.009 E4.88074 ; perimeter
G1 X96.844 Y106.794 E4.91472 ; perimeter
G1 X96.130 Y105.495 E4.92439 ; perimeter
G1 X84.215 Y89.048 E5.05700 ; perimeter
G1 X84.175 Y88.992 E5.05746 ; perimeter
G1 Z1.000 F6000.000 ; move to next layer (9)
G1 X84.175 Y88.992 ; move to first perimeter point
G1 X115.831 Y88.992 F6000.000 E5.26415 ; perimeter
G1 X101.126 Y109.672 E5.42984 ; perimeter
G1 X100.409 Y111.009 E5.43974 ; perimeter
G1 X99.870 Y111.009 E5.44326 ; perimeter
G1 X96.928 Y106.946 E5.47601 ; perimeter
G1 X96.130 Y105.495 E5.48682 ; perimeter
G1 X84.215 Y89.048 E5.61944 ; perimeter
G1 X84.175 Y88.992 E5.61989 ; perimeter
G1 Z1.100 F6000.000 ; move to next layer (10)
G1 X84.175 Y88.992 ; move to first perimeter point
G1 X115.831 Y88.992 F6000.000 E5.82658 ; perimeter
G1 X101.235 Y109.519 E5.99105 ; perimeter
G1 X100.435 Y111.009 E6.00208 ; perimeter
G1 X99.844 Y111.009 E6.00595 ; perimeter
G1 X97.012 Y107.099 E6.03747 ; perimeter
G1 X96.130 Y105.495 E6.04942 ; perimeter
G1 X84.215 Y89.048 E6.18203 ; perimeter
G1 X84.175 Y88.992 E6.18248 ; perimeter
G1 Z1.200 F6000.000 ; move to next layer (11)
G1 X84.175 Y88.991 ; move to first perimeter point
G1 X115.831 Y88.992 F6000.000 E6.38918 ; perimeter
G1 X101.343 Y109.366 E6.55242 ; perimeter
G1 X100.462 Y111.009 E6.56459 ; perimeter
G1 X99.817 Y111.009 E6.56880 ; perimeter
G1 X97.095 Y107.252 E6.59909 ; perimeter
G1 X96.130 Y105.495 E6.61217 ; perimeter
G1 X84.215 Y89.048 E6.74479 ; perimeter
G1 X84.175 Y88.991 E6.74524 ; perimeter
G1 Z1.300 F6000.000 ; move to next layer (12)
G1 X84.175 Y88.991 ; move to first perimeter point
G1 X115.831 Y88.992 F6000.000 E6.95194 ; perimeter
G1 X101.452 Y109.214 E7.11395 ; perimeter
G1 X100.489 Y111.009 E7.12725 ; perimeter
G1 X99.790 Y111.009 E7.13181 ; perimeter
G1 X97.179 Y107.404 E7.16087 ; perimeter
G1 X96.130 Y105.495 E7.17509 ; perimeter
G1 X84.215 Y89.048 E7.30771 ; perimeter
G1 X84.175 Y88.991 E7.30816 ; perimeter
G1 Z1.400 F6000.000 ; move to next layer (13)
G1 X84.175 Y88.991 ; move to first perimeter point
G1 X115.831 Y88.992 F6000.000 E7.51486 ; perimeter
G1 X101.560 Y109.061 E7.67565 ; perimeter
G1 X100.515 Y111.009 E7.69008 ; perimeter
G1 X99.764 Y111.009 E7.69499 ; perimeter
G1 X97.263 Y107.557 E7.72281 ; perimeter
G1 X96.130 Y105.495 E7.73818 ; perimeter
G1 X84.215 Y89.048 E7.87079 ; perimeter
G1 X84.175 Y88.991 E7.87124 ; perimeter
G1 Z1.500 F6000.000 ; move to next layer (14)
G1 X84.175 Y88.991 ; move to first perimeter point
G1 X115.831 Y88.992 F6000.000 E8.07794 ; perimeter
G1 X101.669 Y108.908 E8.23751 ; perimeter
G1 X100.542 Y111.009 E8.25307 ; perimeter
G1 X99.737 Y111.009 E8.25833 ; perimeter
G1 X97.347 Y107.710 E8.28492 ; perimeter
G1 X96.130 Y105.495 E8.30142 ; perimeter
G1 X84.215 Y89.048 E8.43403 ; perimeter
G1 X84.175 Y88.991 E8.43449 ; perimeter
G1 Z1.600 F6000.000 ; move to next layer (15)
G1 X84.175 Y88.991 ; move to first perimeter point
G1 X115.831 Y88.992 F6000.000 E8.64118 ; perimeter
G1 X101.777 Y108.755 E8.79953 ; perimeter
G1 X100.568 Y111.009 E8.81622 ; perimeter
G1 X99.710 Y111.009 E8.82183 ; perimeter
G1 X97.431 Y107.863 E8.84719 ; perimeter
G1 X96.130 Y105.495 E8.86483 ; perimeter
G1 X84.215 Y89.048 E8.99744 ; perimeter
G1 X84.175 Y88.991 E8.99789 ; perimeter
G1 Z1.700 F6000.000 ; move to next layer (16)
G1 X84.175 Y88.991 ; move to first perimeter point
G1 X115.831 Y88.992 F6000.000 E9.20459 ; perimeter
G1 X101.886 Y108.603 E9.36171 ; perimeter
G1 X100.595 Y111.009 E9.37954 ; perimeter
G1 X99.684 Y111.009 E9.38549 ; perimeter
G1 X97.515 Y108.015 E9.40962 ; perimeter
G1 X96.130 Y105.495 E9.42840 ; perimeter
G1 X84.215 Y89.048 E9.56101 ; perimeter
G1 X84.175 Y88.991 E9.56147 ; perimeter
G1 Z1.800 F6000.000 ; move to next layer (17)
G1 X84.175 Y88.991 ; move to first perimeter point
G1 X115.831 Y88.992 F6000.000 E9.76816 ; perimeter
G1 X101.995 Y108.450 E9.92406 ; perimeter
G1 X100.622 Y111.009 E9.94302 ; perimeter
G1 X99.657 Y111.009 E9.94932 ; perimeter
G1 X97.599 Y108.168 E9.97222 ; perimeter
G1 X96.130 Y105.495 E9.99213 ; perimeter
G1 X84.215 Y89.048 E10.12475 ; perimeter
G1 X84.175 Y88.991 E10.12520 ; perimeter
G1 Z1.900 F6000.000 ; move to next layer (18)
G1 X84.175 Y88.991 ; move to first perimeter point
G1 X115.831 Y88.992 F6000.000 E10.33190 ; perimeter
G1 X102.103 Y108.297 E10.48657 ; perimeter
G1 X100.648 Y111.009 E10.50666 ; perimeter
G1 X99.630 Y111.009 E10.51331 ; perimeter
G1 X97.683 Y108.321 E10.53498 ; perimeter
G1 X96.130 Y105.495 E10.55603 ; perimeter
G1 X84.215 Y89.048 E10.68864 ; perimeter
G1 X84.175 Y88.991 E10.68910 ; perimeter
G1 Z2.000 F6000.000 ; move to next layer (19)
G1 X84.175 Y88.991 ; move to first perimeter point
G1 X115.831 Y88.992 F6000.000 E10.89579 ; perimeter
G1 X102.212 Y108.145 E11.04924 ; perimeter
G1 X100.675 Y111.009 E11.07046 ; perimeter
G1 X99.604 Y111.009 E11.07746 ; perimeter
G1 X97.767 Y108.473 E11.09790 ; perimeter
G1 X96.130 Y105.495 E11.12009 ; perimeter
G1 X84.215 Y89.048 E11.25270 ; perimeter
G1 X84.175 Y88.991 E11.25315 ; perimeter
G1 Z2.100 F6000.000 ; move to next layer (20)
G1 X84.175 Y88.991 ; move to first perimeter point
G1 X115.831 Y88.992 F6000.000 E11.45985 ; perimeter
G1 X102.320 Y107.992 E11.61208 ; perimeter
G1 X100.702 Y111.009 E11.63443 ; perimeter
G1 X99.577 Y111.009 E11.64177 ; perimeter
G1 X97.851 Y108.626 E11.66098 ; perimeter
G1 X96.130 Y105.495 E11.68431 ; perimeter
G1 X84.215 Y89.048 E11.81692 ; perimeter
G1 X84.175 Y88.991 E11.81738 ; perimeter
G1 Z2.200 F6000.000 ; move to next layer (21)
G1 X84.175 Y88.991 ; move to first perimeter point
G1 X115.831 Y88.992 F6000.000 E12.02407 ; perimeter
G1 X102.429 Y107.839 E12.17508 ; perimeter
G1 X100.728 Y111.009 E12.19856 ; perimeter
G1 X99.550 Y111.009 E12.20625 ; perimeter
G1 X97.935 Y108.779 E12.22423 ; perimeter
G1 X96.130 Y105.495 E12.24870 ; perimeter
G1 X84.215 Y89.048 E12.38131 ; perimeter
G1 X84.175 Y88.991 E12.38176 ; perimeter
G1 Z2.300 F6000.000 ; move to next layer (22)
G1 X84.175 Y88.991 ; move to first perimeter point
G1 X115.831 Y88.992 F6000.000 E12.58846 ; perimeter
G1 X102.538 Y107.686 E12.73824 ; perimeter
G1 X100.755 Y111.009 E12.76285 ; perimeter
G1 X99.524 Y111.009 E12.77089 ; perimeter
G1 X98.019 Y108.932 E12.78764 ; perimeter
G1 X96.130 Y105.495 E12.81324 ; perimeter
G1 X84.215 Y89.048 E12.94586 ; perimeter
G1 X84.175 Y88.991 E12.94631 ; perimeter
G1 Z2.400 F6000.000 ; move to next layer (23)
G1 X84.175 Y88.991 ; move to first perimeter point
G1 X115.831 Y88.992 F6000.000 E13.15300 ; perimeter
G1 X102.646 Y107.534 E13.30156 ; perimeter
G1 X100.782 Y111.009 E13.32731 ; perimeter
G1 X99.497 Y111.009 E13.33570 ; perimeter
G1 X98.103 Y109.084 E13.35121 ; perimeter
G1 X96.130 Y105.495 E13.37795 ; perimeter
G1 X84.215 Y89.048 E13.51057 ; perimeter
G1 X84.175 Y88.991 E13.51102 ; perimeter
G1 Z2.500 F6000.000 ; move to next layer (24)
G1 X84.175 Y88.991 ; move to first perimeter point
G1 X115.831 Y88.992 F6000.000 E13.71771 ; perimeter
G1 X102.755 Y107.381 E13.86505 ; perimeter
G1 X100.808 Y111.009 E13.89193 ; perimeter
G1 X99.471 Y111.009 E13.90066 ; perimeter
G1 X98.187 Y109.237 E13.91495 ; perimeter
G1 X96.130 Y105.495 E13.94283 ; perimeter
G1 X84.215 Y89.048 E14.07544 ; perimeter
G1 X84.175 Y88.991 E14.07589 ; perimeter
G1 Z2.600 F6000.000 ; move to next layer (25)
G1 X84.175 Y88.991 ; move to first perimeter point
G1 X115.831 Y88.992 F6000.000 E14.28259 ; perimeter
G1 X102.863 Y107.228 E14.42870 ; perimeter
G1 X100.835 Y111.009 E14.45671 ; perimeter
G1 X99.444 Y111.009 E14.46579 ; perimeter
G1 X98.271 Y109.390 E14.47884 ; perimeter
G1 X96.130 Y105.495 E14.50786 ; perimeter
G1 X84.215 Y89.048 E14.64047 ; perimeter
G1 X84.175 Y88.991 E14.64093 ; perimeter
G1 Z2.700 F6000.000 ; move to next layer (26)
G1 X84.175 Y88.991 ; move to first perimeter point
G1 X115.831 Y88.992 F6000.000 E14.84762 ; perimeter
G1 X102.972 Y107.076 E14.99251 ; perimeter
G1 X100.862 Y111.009 E15.02165 ; perimeter
G1 X99.417 Y111.009 E15.03108 ; perimeter
G1 X98.355 Y109.542 E15.04290 ; perimeter
G1 X96.130 Y105.495 E15.07306 ; perimeter
G1 X84.215 Y89.048 E15.20567 ; perimeter
G1 X84.175 Y88.991 E15.20612 ; perimeter
G1 Z2.800 F6000.000 ; move to next layer (27)
G1 X84.175 Y88.991 ; move to first perimeter point
G1 X115.831 Y88.992 F6000.000 E15.41282 ; perimeter
G1 X103.080 Y106.923 E15.55648 ; perimeter
G1 X100.888 Y111.009 E15.58676 ; perimeter
G1 X99.391 Y111.009 E15.59654 ; perimeter
G1 X98.439 Y109.695 E15.60713 ; perimeter
G1 X96.130 Y105.495 E15.63842 ; perimeter
G1 X84.215 Y89.048 E15.77103 ; perimeter
G1 X84.175 Y88.991 E15.77148 ; perimeter
G1 Z2.900 F6000.000 ; move to next layer (28)
G1 X84.175 Y88.991 ; move to first perimeter point
G1 X115.831 Y88.992 F6000.000 E15.97818 ; perimeter
G1 X103.189 Y106.770 E16.12062 ; perimeter
G1 X100.915 Y111.009 E16.15203 ; perimeter
G1 X99.364 Y111.009 E16.16215 ; perimeter
G1 X98.523 Y109.848 E16.17151 ; perimeter
G1 X96.130 Y105.495 E16.20394 ; perimeter
G1 X84.215 Y89.048 E16.33656 ; perimeter
G1 X84.175 Y88.991 E16.33701 ; perimeter
G1 Z3.000 F6000.000 ; move to next layer (29)
G1 X84.175 Y88.991 ; move to first perimeter point
G1 X115.831 Y88.992 F6000.000 E16.54370 ; perimeter
G1 X103.298 Y106.617 E16.68492 ; perimeter
G1 X100.941 Y111.009 E16.71746 ; perimeter
G1 X99.337 Y111.009 E16.72793 ; perimeter
G1 X98.607 Y110.000 E16.73606 ; perimeter
G1 X96.130 Y105.495 E16.76963 ; perimeter
G1 X84.215 Y89.048 E16.90224 ; perimeter
G1 X84.175 Y88.991 E16.90269 ; perimeter
G1 Z3.100 F6000.000 ; move to next layer (30)
G1 X84.175 Y88.991 ; move to first perimeter point
G1 X115.831 Y88.992 F6000.000 E17.10939 ; perimeter
G1 X103.406 Y106.465 E17.24938 ; perimeter
G1 X100.968 Y111.009 E17.28305 ; perimeter
G1 X99.311 Y111.009 E17.29388 ; perimeter
G1 X98.691 Y110.153 E17.30077 ; perimeter
G1 X96.130 Y105.495 E17.33548 ; perimeter
G1 X84.215 Y89.048 E17.46809 ; perimeter
G1 X84.175 Y88.991 E17.46854 ; perimeter
G1 Z3.200 F6000.000 ; move to next layer (31)
G1 X84.175 Y88.991 ; move to first perimeter point
G1 X115.831 Y88.992 F6000.000 E17.67524 ; perimeter
G1 X103.515 Y106.312 E17.81401 ; perimeter
G1 X100.995 Y111.009 E17.84881 ; perimeter
G1 X99.284 Y111.009 E17.85998 ; perimeter
G1 X98.775 Y110.306 E17.86565 ; perimeter
G1 X96.130 Y105.495 E17.90149 ; perimeter
G1 X84.215 Y89.048 E18.03410 ; perimeter
G1 X84.175 Y88.991 E18.03456 ; perimeter
G1 Z3.300 F6000.000 ; move to next layer (32)
G1 X84.175 Y88.991 ; move to first perimeter point
G1 X115.831 Y88.992 F6000.000 E18.24125 ; perimeter
G1 X103.623 Y106.159 E18.37880 ; perimeter
G1 X101.021 Y111.009 E18.41473 ; perimeter
G1 X99.257 Y111.009 E18.42625 ; perimeter
G1 X98.859 Y110.459 E18.43068 ; perimeter
G1 X96.130 Y105.495 E18.46767 ; perimeter
G1 X84.215 Y89.048 E18.60028 ; perimeter
G1 X84.175 Y88.991 E18.60073 ; perimeter
G1 Z3.400 F6000.000 ; move to next layer (33)
G1 X84.175 Y88.991 ; move to first perimeter point
G1 X115.831 Y88.992 F6000.000 E18.80743 ; perimeter
G1 X103.732 Y106.007 E18.94375 ; perimeter
G1 X101.048 Y111.009 E18.98081 ; perimeter
G1 X99.231 Y111.009 E18.99268 ; perimeter
G1 X98.943 Y110.611 E18.99588 ; perimeter
G1 X96.130 Y105.495 E19.03400 ; perimeter
G1 X84.215 Y89.048 E19.16661 ; perimeter
G1 X84.175 Y88.991 E19.16707 ; perimeter
G1 Z3.500 F6000.000 ; move to next layer (34)
G1 X84.175 Y88.991 ; move to first perimeter point
G1 X115.831 Y88.992 F6000.000 E19.37376 ; perimeter
G1 X103.841 Y105.854 E19.50886 ; perimeter
G1 X101.075 Y111.009 E19.54706 ; perimeter
G1 X99.204 Y111.009 E19.55927 ; perimeter
G1 X99.027 Y110.764 E19.56124 ; perimeter
G1 X96.130 Y105.495 E19.60050 ; perimeter
G1 X84.215 Y89.048 E19.73311 ; perimeter
G1 X84.175 Y88.991 E19.73357 ; perimeter
G1 Z3.600 F6000.000 ; move to next layer (35)
G1 X84.175 Y88.991 ; move to first perimeter point
G1 X115.831 Y88.992 F6000.000 E19.94026 ; perimeter
G1 X103.949 Y105.701 E20.07414 ; perimeter
G1 X101.101 Y111.009 E20.11347 ; perimeter
G1 X99.161 Y111.009 E20.12613 ; perimeter
G1 X96.130 Y105.495 E20.16721 ; perimeter
G1 X84.215 Y89.048 E20.29983 ; perimeter
G1 X84.175 Y88.991 E20.30028 ; perimeter
G1 Z3.700 F6000.000 ; move to next layer (36)
G1 X84.175 Y88.991 ; move to first perimeter point
G1 X115.831 Y88.992 F6000.000 E20.50697 ; perimeter
G1 X104.058 Y105.548 E20.63963 ; perimeter
G1 X101.128 Y111.009 E20.68009 ; perimeter
G1 X99.161 Y111.009 E20.69293 ; perimeter
G1 X96.130 Y105.495 E20.73401 ; perimeter
G1 X84.215 Y89.048 E20.86662 ; perimeter
G1 X84.175 Y88.991 E20.86707 ; perimeter

; filament used = 20.9mm (0.1cm3)

; acceleration = 0
; bed_size = 200,200
; bed_temperature = 0
; bottom_solid_layers = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 1.16
; bridge_speed = 100
; brim_width = 0
; complete_objects = 
; cooling = 
; disable_fan_first_layers = 0
; duplicate = 1
; duplicate_distance = 6
; duplicate_grid = 1,1
; end_gcode = 
; external_perimeter_speed = 100
; extra_perimeters = 
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0
; fan_always_on = 
; fan_below_layer_time = 0
; filament_diameter = 3
; fill_angle = 45
; fill_density = 0
; fill_pattern = rectilinear
; first_layer_bed_temperature = 0
; first_layer_extrusion_width = 0
; first_layer_height = 100%
; first_layer_speed = 100
; first_layer_temperature = 0
; g0 = 0
; gcode_arcs = 0
; gcode_comments = 1
; gcode_flavor = reprap
; infill_acceleration = 50
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0
; infill_speed = 100
; layer_gcode = 
; layer_height = .1
; max_fan_speed = 100
; min_fan_speed = 100
; min_print_speed = 1
; min_skirt_length = 0
; notes = This config has a workaround for the extrusion retraction compensation bug for the first layer... be sure to comment out those 3 lines IF the bug has been fixed.
; nozzle_diameter = .345
; only_retract_when_crossing_perimeters = 1
; output_filename_format = [input_filename_base]_[timestamp].gcode
; perimeter_acceleration = 25
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_speed = 100
; perimeters = 1
; post_process = 
; print_center = 100,100
; randomize_start = 
; retract_before_travel = 0
; retract_length = 0
; retract_length_toolchange = 0
; retract_lift = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 26
; rotate = 0
; scale = 1
; skirt_distance = 0
; skirt_height = 0
; skirts = 0
; slowdown_below_layer_time = 0
; small_perimeter_speed = 100
; solid_fill_pattern = rectilinear
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_speed = 100
; start_gcode = G92 E0\nG1 E100\nG1 E0
; support_material = 
; support_material_angle = 45
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_pattern = honeycomb
; support_material_spacing = 0
; support_material_threshold = 0
; temperature = 0,0,0
; threads = 4
; top_solid_infill_speed = 100
; top_solid_layers = 0
; travel_speed = 100
; use_relative_e_distances = 0
; vibration_limit = 25
; z_offset = 0
