; generated by Slic3r 0.9.8-dev on 2012-11-23 at 14:18:57

; This config has a workaround for the extrusion retraction compensation bug for the first layer... be sure to comment out those 3 lines IF the bug has been fixed.

; layer_height = .1
; perimeters = 1
; top_solid_layers = 0
; bottom_solid_layers = 0
; fill_density = 0
; perimeter_speed = 100
; infill_speed = 100
; travel_speed = 100
; scale = 1
; nozzle_diameter = .345
; filament_diameter = 3
; extrusion_multiplier = 1
; perimeters extrusion width = 0.48mm
; infill extrusion width = 0.48mm
; first layer extrusion width = 0.48mm

G92 E0
G1 E100
G1 E0
G90 ; use absolute coordinates
G21 ; set units to millimeters
G92 E0 ; reset extrusion distance
M82 ; use absolute distances for extrusion
G1 Z0.100 F6000.000 ; move to next layer (0)
G1 X94.241 Y96.174 ; move to first perimeter point
G1 X105.239 Y103.759 F6000.000 E0.08723 ; perimeter
G1 X94.241 Y103.759 E0.15904 ; perimeter
G1 X94.241 Y96.243 E0.20812 ; perimeter
G1 X94.241 Y96.174 E0.20857 ; perimeter
G1 Z0.200 F6000.000 ; move to next layer (1)
G1 X94.241 Y96.153 ; move to first perimeter point
G1 X105.269 Y103.759 F6000.000 E0.29604 ; perimeter
G1 X94.241 Y103.759 E0.36804 ; perimeter
G1 X94.241 Y96.222 E0.41725 ; perimeter
G1 X94.241 Y96.153 E0.41770 ; perimeter
G1 Z0.300 F6000.000 ; move to next layer (2)
G1 X94.241 Y96.132 ; move to first perimeter point
G1 X105.299 Y103.759 F6000.000 E0.50541 ; perimeter
G1 X94.241 Y103.759 E0.57761 ; perimeter
G1 X94.241 Y96.202 E0.62696 ; perimeter
G1 X94.241 Y96.132 E0.62741 ; perimeter
G1 Z0.400 F6000.000 ; move to next layer (3)
G1 X94.241 Y96.112 ; move to first perimeter point
G1 X105.329 Y103.759 F6000.000 E0.71535 ; perimeter
G1 X94.241 Y103.759 E0.78775 ; perimeter
G1 X94.241 Y96.181 E0.83723 ; perimeter
G1 X94.241 Y96.112 E0.83768 ; perimeter
G1 Z0.500 F6000.000 ; move to next layer (4)
G1 X94.241 Y96.091 ; move to first perimeter point
G1 X105.359 Y103.759 F6000.000 E0.92587 ; perimeter
G1 X94.241 Y103.759 E0.99846 ; perimeter
G1 X94.241 Y96.160 E1.04807 ; perimeter
G1 X94.241 Y96.091 E1.04853 ; perimeter
G1 Z0.600 F6000.000 ; move to next layer (5)
G1 X94.241 Y96.070 ; move to first perimeter point
G1 X105.389 Y103.759 F6000.000 E1.13695 ; perimeter
G1 X94.241 Y103.759 E1.20974 ; perimeter
G1 X94.241 Y96.139 E1.25949 ; perimeter
G1 X94.241 Y96.070 E1.25994 ; perimeter
G1 Z0.700 F6000.000 ; move to next layer (6)
G1 X94.241 Y96.050 ; move to first perimeter point
G1 X105.419 Y103.759 F6000.000 E1.34860 ; perimeter
G1 X94.241 Y103.759 E1.42158 ; perimeter
G1 X94.241 Y96.119 E1.47147 ; perimeter
G1 X94.241 Y96.050 E1.47192 ; perimeter
G1 Z0.800 F6000.000 ; move to next layer (7)
G1 X94.241 Y96.029 ; move to first perimeter point
G1 X105.449 Y103.759 F6000.000 E1.56082 ; perimeter
G1 X94.241 Y103.759 E1.63400 ; perimeter
G1 X94.241 Y96.098 E1.68402 ; perimeter
G1 X94.241 Y96.029 E1.68447 ; perimeter
G1 Z0.900 F6000.000 ; move to next layer (8)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X94.580 Y96.241 F6000.000 E1.68668 ; perimeter
G1 X105.479 Y103.759 E1.77313 ; perimeter
G1 X94.241 Y103.759 E1.84651 ; perimeter
G1 X94.241 Y96.311 E1.89514 ; perimeter
G1 X94.241 Y96.241 E1.89559 ; perimeter
G1 Z1.000 F6000.000 ; move to next layer (9)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X94.610 Y96.241 F6000.000 E1.89799 ; perimeter
G1 X105.509 Y103.759 E1.98445 ; perimeter
G1 X94.241 Y103.759 E2.05802 ; perimeter
G1 X94.241 Y96.311 E2.10665 ; perimeter
G1 X94.241 Y96.241 E2.10710 ; perimeter
G1 Z1.100 F6000.000 ; move to next layer (10)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X94.640 Y96.241 F6000.000 E2.10970 ; perimeter
G1 X105.539 Y103.759 E2.19615 ; perimeter
G1 X94.241 Y103.759 E2.26992 ; perimeter
G1 X94.241 Y96.311 E2.31855 ; perimeter
G1 X94.241 Y96.241 E2.31901 ; perimeter
G1 Z1.200 F6000.000 ; move to next layer (11)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X94.670 Y96.241 F6000.000 E2.32180 ; perimeter
G1 X105.569 Y103.759 E2.40825 ; perimeter
G1 X94.241 Y103.759 E2.48222 ; perimeter
G1 X94.241 Y96.311 E2.53085 ; perimeter
G1 X94.241 Y96.241 E2.53130 ; perimeter
G1 Z1.300 F6000.000 ; move to next layer (12)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X94.700 Y96.241 F6000.000 E2.53429 ; perimeter
G1 X105.599 Y103.759 E2.62075 ; perimeter
G1 X94.241 Y103.759 E2.69491 ; perimeter
G1 X94.241 Y96.311 E2.74354 ; perimeter
G1 X94.241 Y96.241 E2.74399 ; perimeter
G1 Z1.400 F6000.000 ; move to next layer (13)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X94.730 Y96.241 F6000.000 E2.74718 ; perimeter
G1 X104.945 Y103.286 E2.82820 ; perimeter
G1 X105.417 Y103.759 E2.83256 ; perimeter
G1 X94.241 Y103.759 E2.90553 ; perimeter
G1 X94.241 Y96.311 E2.95416 ; perimeter
G1 X94.241 Y96.241 E2.95461 ; perimeter
G1 Z1.500 F6000.000 ; move to next layer (14)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X94.760 Y96.241 F6000.000 E2.95800 ; perimeter
G1 X104.878 Y103.220 E3.03825 ; perimeter
G1 X105.417 Y103.759 E3.04323 ; perimeter
G1 X94.241 Y103.759 E3.11620 ; perimeter
G1 X94.241 Y96.311 E3.16483 ; perimeter
G1 X94.241 Y96.241 E3.16528 ; perimeter
G1 Z1.600 F6000.000 ; move to next layer (15)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X94.790 Y96.241 F6000.000 E3.16886 ; perimeter
G1 X104.811 Y103.153 E3.24835 ; perimeter
G1 X105.417 Y103.759 E3.25394 ; perimeter
G1 X94.241 Y103.759 E3.32691 ; perimeter
G1 X94.241 Y96.311 E3.37554 ; perimeter
G1 X94.241 Y96.241 E3.37599 ; perimeter
G1 Z1.700 F6000.000 ; move to next layer (16)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X94.820 Y96.241 F6000.000 E3.37977 ; perimeter
G1 X104.745 Y103.086 E3.45849 ; perimeter
G1 X105.417 Y103.759 E3.46469 ; perimeter
G1 X94.241 Y103.759 E3.53766 ; perimeter
G1 X94.241 Y96.311 E3.58629 ; perimeter
G1 X94.241 Y96.241 E3.58675 ; perimeter
G1 Z1.800 F6000.000 ; move to next layer (17)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X94.850 Y96.241 F6000.000 E3.59072 ; perimeter
G1 X104.678 Y103.020 E3.66867 ; perimeter
G1 X105.417 Y103.759 E3.67550 ; perimeter
G1 X94.241 Y103.759 E3.74847 ; perimeter
G1 X94.241 Y96.311 E3.79710 ; perimeter
G1 X94.241 Y96.241 E3.79755 ; perimeter
G1 Z1.900 F6000.000 ; move to next layer (18)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X94.880 Y96.241 F6000.000 E3.80172 ; perimeter
G1 X104.611 Y102.953 E3.87890 ; perimeter
G1 X105.417 Y103.759 E3.88634 ; perimeter
G1 X94.241 Y103.759 E3.95931 ; perimeter
G1 X94.241 Y96.311 E4.00794 ; perimeter
G1 X94.241 Y96.241 E4.00839 ; perimeter
G1 Z2.000 F6000.000 ; move to next layer (19)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X94.910 Y96.241 F6000.000 E4.01276 ; perimeter
G1 X104.545 Y102.886 E4.08918 ; perimeter
G1 X105.417 Y103.759 E4.09723 ; perimeter
G1 X94.241 Y103.759 E4.17020 ; perimeter
G1 X94.241 Y96.311 E4.21883 ; perimeter
G1 X94.241 Y96.241 E4.21928 ; perimeter
G1 Z2.100 F6000.000 ; move to next layer (20)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X94.940 Y96.241 F6000.000 E4.22384 ; perimeter
G1 X104.478 Y102.820 E4.29950 ; perimeter
G1 X105.417 Y103.759 E4.30817 ; perimeter
G1 X94.241 Y103.759 E4.38114 ; perimeter
G1 X94.241 Y96.311 E4.42977 ; perimeter
G1 X94.241 Y96.241 E4.43022 ; perimeter
G1 Z2.200 F6000.000 ; move to next layer (21)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X94.970 Y96.241 F6000.000 E4.43497 ; perimeter
G1 X104.411 Y102.753 E4.50986 ; perimeter
G1 X105.417 Y103.759 E4.51915 ; perimeter
G1 X94.241 Y103.759 E4.59212 ; perimeter
G1 X94.241 Y96.311 E4.64075 ; perimeter
G1 X94.241 Y96.241 E4.64120 ; perimeter
G1 Z2.300 F6000.000 ; move to next layer (22)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X95.000 Y96.241 F6000.000 E4.64615 ; perimeter
G1 X104.345 Y102.686 E4.72027 ; perimeter
G1 X105.417 Y103.759 E4.73017 ; perimeter
G1 X94.241 Y103.759 E4.80314 ; perimeter
G1 X94.241 Y96.311 E4.85177 ; perimeter
G1 X94.241 Y96.241 E4.85222 ; perimeter
G1 Z2.400 F6000.000 ; move to next layer (23)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X95.030 Y96.241 F6000.000 E4.85737 ; perimeter
G1 X104.278 Y102.620 E4.93073 ; perimeter
G1 X105.417 Y103.759 E4.94124 ; perimeter
G1 X94.241 Y103.759 E5.01421 ; perimeter
G1 X94.241 Y96.311 E5.06284 ; perimeter
G1 X94.241 Y96.241 E5.06329 ; perimeter
G1 Z2.500 F6000.000 ; move to next layer (24)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X95.060 Y96.241 F6000.000 E5.06864 ; perimeter
G1 X104.211 Y102.553 E5.14122 ; perimeter
G1 X105.417 Y103.759 E5.15236 ; perimeter
G1 X94.241 Y103.759 E5.22533 ; perimeter
G1 X94.241 Y96.311 E5.27396 ; perimeter
G1 X94.241 Y96.241 E5.27441 ; perimeter
G1 Z2.600 F6000.000 ; move to next layer (25)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X95.090 Y96.241 F6000.000 E5.27995 ; perimeter
G1 X104.145 Y102.486 E5.35177 ; perimeter
G1 X105.417 Y103.759 E5.36352 ; perimeter
G1 X94.241 Y103.759 E5.43648 ; perimeter
G1 X94.241 Y96.311 E5.48511 ; perimeter
G1 X94.241 Y96.241 E5.48557 ; perimeter
G1 Z2.700 F6000.000 ; move to next layer (26)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X95.120 Y96.241 F6000.000 E5.49130 ; perimeter
G1 X104.078 Y102.420 E5.56236 ; perimeter
G1 X105.417 Y103.759 E5.57472 ; perimeter
G1 X94.241 Y103.759 E5.64769 ; perimeter
G1 X94.241 Y96.311 E5.69632 ; perimeter
G1 X94.241 Y96.241 E5.69677 ; perimeter
G1 Z2.800 F6000.000 ; move to next layer (27)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X95.150 Y96.241 F6000.000 E5.70270 ; perimeter
G1 X104.011 Y102.353 E5.77299 ; perimeter
G1 X105.417 Y103.759 E5.78597 ; perimeter
G1 X94.241 Y103.759 E5.85894 ; perimeter
G1 X94.241 Y96.311 E5.90757 ; perimeter
G1 X94.241 Y96.241 E5.90802 ; perimeter
G1 Z2.900 F6000.000 ; move to next layer (28)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X95.180 Y96.241 F6000.000 E5.91415 ; perimeter
G1 X103.945 Y102.286 E5.98367 ; perimeter
G1 X105.417 Y103.759 E5.99726 ; perimeter
G1 X94.241 Y103.759 E6.07023 ; perimeter
G1 X94.241 Y96.311 E6.11886 ; perimeter
G1 X94.241 Y96.241 E6.11931 ; perimeter
G1 Z3.000 F6000.000 ; move to next layer (29)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X95.210 Y96.241 F6000.000 E6.12564 ; perimeter
G1 X103.878 Y102.220 E6.19439 ; perimeter
G1 X105.417 Y103.759 E6.20860 ; perimeter
G1 X94.241 Y103.759 E6.28157 ; perimeter
G1 X94.241 Y96.311 E6.33020 ; perimeter
G1 X94.241 Y96.241 E6.33065 ; perimeter
G1 Z3.100 F6000.000 ; move to next layer (30)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X95.240 Y96.241 F6000.000 E6.33717 ; perimeter
G1 X103.811 Y102.153 E6.40516 ; perimeter
G1 X105.417 Y103.759 E6.41998 ; perimeter
G1 X94.241 Y103.759 E6.49295 ; perimeter
G1 X94.241 Y96.311 E6.54158 ; perimeter
G1 X94.241 Y96.241 E6.54203 ; perimeter
G1 Z3.200 F6000.000 ; move to next layer (31)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X95.270 Y96.241 F6000.000 E6.54875 ; perimeter
G1 X103.745 Y102.086 E6.61597 ; perimeter
G1 X105.417 Y103.759 E6.63141 ; perimeter
G1 X94.241 Y103.759 E6.70438 ; perimeter
G1 X94.241 Y96.311 E6.75301 ; perimeter
G1 X94.241 Y96.241 E6.75346 ; perimeter
G1 Z3.300 F6000.000 ; move to next layer (32)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X95.300 Y96.241 F6000.000 E6.76037 ; perimeter
G1 X103.678 Y102.020 E6.82683 ; perimeter
G1 X105.417 Y103.759 E6.84288 ; perimeter
G1 X94.241 Y103.759 E6.91585 ; perimeter
G1 X94.241 Y96.311 E6.96448 ; perimeter
G1 X94.241 Y96.241 E6.96493 ; perimeter
G1 Z3.400 F6000.000 ; move to next layer (33)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X95.330 Y96.241 F6000.000 E6.97204 ; perimeter
G1 X103.611 Y101.953 E7.03773 ; perimeter
G1 X105.417 Y103.759 E7.05440 ; perimeter
G1 X94.241 Y103.759 E7.12737 ; perimeter
G1 X94.241 Y96.311 E7.17600 ; perimeter
G1 X94.241 Y96.241 E7.17645 ; perimeter
G1 Z3.500 F6000.000 ; move to next layer (34)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X95.360 Y96.241 F6000.000 E7.18375 ; perimeter
G1 X103.545 Y101.886 E7.24867 ; perimeter
G1 X105.417 Y103.759 E7.26596 ; perimeter
G1 X94.241 Y103.759 E7.33893 ; perimeter
G1 X94.241 Y96.311 E7.38756 ; perimeter
G1 X94.241 Y96.241 E7.38801 ; perimeter
G1 Z3.600 F6000.000 ; move to next layer (35)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X95.390 Y96.241 F6000.000 E7.39551 ; perimeter
G1 X103.478 Y101.820 E7.45966 ; perimeter
G1 X105.417 Y103.759 E7.47757 ; perimeter
G1 X94.241 Y103.759 E7.55054 ; perimeter
G1 X94.241 Y96.311 E7.59917 ; perimeter
G1 X94.241 Y96.241 E7.59962 ; perimeter
G1 Z3.700 F6000.000 ; move to next layer (36)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X95.420 Y96.241 F6000.000 E7.60731 ; perimeter
G1 X103.411 Y101.753 E7.67070 ; perimeter
G1 X105.417 Y103.759 E7.68922 ; perimeter
G1 X94.241 Y103.759 E7.76219 ; perimeter
G1 X94.241 Y96.311 E7.81082 ; perimeter
G1 X94.241 Y96.241 E7.81127 ; perimeter
G1 Z3.800 F6000.000 ; move to next layer (37)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X95.450 Y96.241 F6000.000 E7.81916 ; perimeter
G1 X103.345 Y101.686 E7.88178 ; perimeter
G1 X105.417 Y103.759 E7.90092 ; perimeter
G1 X94.241 Y103.759 E7.97388 ; perimeter
G1 X94.241 Y96.311 E8.02251 ; perimeter
G1 X94.241 Y96.241 E8.02297 ; perimeter
G1 Z3.900 F6000.000 ; move to next layer (38)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X95.480 Y96.241 F6000.000 E8.03105 ; perimeter
G1 X103.278 Y101.620 E8.09291 ; perimeter
G1 X105.417 Y103.759 E8.11266 ; perimeter
G1 X94.241 Y103.759 E8.18563 ; perimeter
G1 X94.241 Y96.311 E8.23426 ; perimeter
G1 X94.241 Y96.241 E8.23471 ; perimeter
G1 Z4.000 F6000.000 ; move to next layer (39)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X95.510 Y96.241 F6000.000 E8.24299 ; perimeter
G1 X103.211 Y101.553 E8.30408 ; perimeter
G1 X105.417 Y103.759 E8.32444 ; perimeter
G1 X94.241 Y103.759 E8.39741 ; perimeter
G1 X94.241 Y96.311 E8.44604 ; perimeter
G1 X94.241 Y96.241 E8.44649 ; perimeter
G1 Z4.100 F6000.000 ; move to next layer (40)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X95.540 Y96.241 F6000.000 E8.45497 ; perimeter
G1 X103.145 Y101.486 E8.51529 ; perimeter
G1 X105.417 Y103.759 E8.53627 ; perimeter
G1 X94.241 Y103.759 E8.60924 ; perimeter
G1 X94.241 Y96.311 E8.65787 ; perimeter
G1 X94.241 Y96.241 E8.65832 ; perimeter
G1 Z4.200 F6000.000 ; move to next layer (41)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X95.570 Y96.241 F6000.000 E8.66700 ; perimeter
G1 X103.078 Y101.420 E8.72655 ; perimeter
G1 X105.417 Y103.759 E8.74815 ; perimeter
G1 X94.241 Y103.759 E8.82112 ; perimeter
G1 X94.241 Y96.311 E8.86975 ; perimeter
G1 X94.241 Y96.241 E8.87020 ; perimeter
G1 Z4.300 F6000.000 ; move to next layer (42)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X95.600 Y96.241 F6000.000 E8.87907 ; perimeter
G1 X103.011 Y101.353 E8.93785 ; perimeter
G1 X105.417 Y103.759 E8.96007 ; perimeter
G1 X94.241 Y103.759 E9.03304 ; perimeter
G1 X94.241 Y96.311 E9.08167 ; perimeter
G1 X94.241 Y96.241 E9.08212 ; perimeter
G1 Z4.400 F6000.000 ; move to next layer (43)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X95.630 Y96.241 F6000.000 E9.09118 ; perimeter
G1 X102.945 Y101.286 E9.14920 ; perimeter
G1 X105.417 Y103.759 E9.17203 ; perimeter
G1 X94.241 Y103.759 E9.24500 ; perimeter
G1 X94.241 Y96.311 E9.29363 ; perimeter
G1 X94.241 Y96.241 E9.29408 ; perimeter
G1 Z4.500 F6000.000 ; move to next layer (44)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X95.660 Y96.241 F6000.000 E9.30334 ; perimeter
G1 X102.878 Y101.220 E9.36060 ; perimeter
G1 X105.417 Y103.759 E9.38404 ; perimeter
G1 X94.241 Y103.759 E9.45701 ; perimeter
G1 X94.241 Y96.311 E9.50564 ; perimeter
G1 X94.241 Y96.241 E9.50609 ; perimeter
G1 Z4.600 F6000.000 ; move to next layer (45)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X95.690 Y96.241 F6000.000 E9.51555 ; perimeter
G1 X102.811 Y101.153 E9.57204 ; perimeter
G1 X105.417 Y103.759 E9.59610 ; perimeter
G1 X94.241 Y103.759 E9.66907 ; perimeter
G1 X94.241 Y96.311 E9.71770 ; perimeter
G1 X94.241 Y96.241 E9.71815 ; perimeter
G1 Z4.700 F6000.000 ; move to next layer (46)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X95.720 Y96.241 F6000.000 E9.72780 ; perimeter
G1 X102.745 Y101.086 E9.78352 ; perimeter
G1 X105.417 Y103.759 E9.80819 ; perimeter
G1 X94.241 Y103.759 E9.88116 ; perimeter
G1 X94.241 Y96.311 E9.92979 ; perimeter
G1 X94.241 Y96.241 E9.93025 ; perimeter
G1 Z4.800 F6000.000 ; move to next layer (47)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X95.750 Y96.241 F6000.000 E9.94009 ; perimeter
G1 X102.678 Y101.020 E9.99505 ; perimeter
G1 X105.417 Y103.759 E10.02034 ; perimeter
G1 X94.241 Y103.759 E10.09331 ; perimeter
G1 X94.241 Y96.311 E10.14194 ; perimeter
G1 X94.241 Y96.241 E10.14239 ; perimeter
G1 Z4.900 F6000.000 ; move to next layer (48)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X95.780 Y96.241 F6000.000 E10.15243 ; perimeter
G1 X102.611 Y100.953 E10.20662 ; perimeter
G1 X105.417 Y103.759 E10.23253 ; perimeter
G1 X94.241 Y103.759 E10.30550 ; perimeter
G1 X94.241 Y96.311 E10.35413 ; perimeter
G1 X94.241 Y96.241 E10.35458 ; perimeter
G1 Z5.000 F6000.000 ; move to next layer (49)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X95.810 Y96.241 F6000.000 E10.36482 ; perimeter
G1 X102.545 Y100.886 E10.41824 ; perimeter
G1 X105.417 Y103.759 E10.44476 ; perimeter
G1 X94.241 Y103.759 E10.51773 ; perimeter
G1 X94.241 Y96.311 E10.56636 ; perimeter
G1 X94.241 Y96.241 E10.56681 ; perimeter
G1 Z5.100 F6000.000 ; move to next layer (50)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X95.840 Y96.241 F6000.000 E10.57725 ; perimeter
G1 X102.478 Y100.820 E10.62990 ; perimeter
G1 X105.417 Y103.759 E10.65704 ; perimeter
G1 X94.241 Y103.759 E10.73001 ; perimeter
G1 X94.241 Y96.311 E10.77864 ; perimeter
G1 X94.241 Y96.241 E10.77909 ; perimeter
G1 Z5.200 F6000.000 ; move to next layer (51)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X95.870 Y96.241 F6000.000 E10.78972 ; perimeter
G1 X102.411 Y100.753 E10.84161 ; perimeter
G1 X105.417 Y103.759 E10.86936 ; perimeter
G1 X94.241 Y103.759 E10.94233 ; perimeter
G1 X94.241 Y96.311 E10.99096 ; perimeter
G1 X94.241 Y96.241 E10.99141 ; perimeter
G1 Z5.300 F6000.000 ; move to next layer (52)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X95.900 Y96.241 F6000.000 E11.00224 ; perimeter
G1 X102.345 Y100.686 E11.05336 ; perimeter
G1 X105.417 Y103.759 E11.08173 ; perimeter
G1 X94.241 Y103.759 E11.15470 ; perimeter
G1 X94.241 Y96.311 E11.20333 ; perimeter
G1 X94.241 Y96.241 E11.20378 ; perimeter
G1 Z5.400 F6000.000 ; move to next layer (53)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X95.930 Y96.241 F6000.000 E11.21480 ; perimeter
G1 X102.278 Y100.620 E11.26516 ; perimeter
G1 X105.417 Y103.759 E11.29414 ; perimeter
G1 X94.241 Y103.759 E11.36711 ; perimeter
G1 X94.241 Y96.311 E11.41574 ; perimeter
G1 X94.241 Y96.241 E11.41619 ; perimeter
G1 Z5.500 F6000.000 ; move to next layer (54)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X95.960 Y96.241 F6000.000 E11.42741 ; perimeter
G1 X102.211 Y100.553 E11.47700 ; perimeter
G1 X105.417 Y103.759 E11.50660 ; perimeter
G1 X94.241 Y103.759 E11.57957 ; perimeter
G1 X94.241 Y96.311 E11.62820 ; perimeter
G1 X94.241 Y96.241 E11.62865 ; perimeter
G1 Z5.600 F6000.000 ; move to next layer (55)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X95.990 Y96.241 F6000.000 E11.64006 ; perimeter
G1 X102.145 Y100.486 E11.68888 ; perimeter
G1 X105.417 Y103.759 E11.71910 ; perimeter
G1 X94.241 Y103.759 E11.79207 ; perimeter
G1 X94.241 Y96.311 E11.84070 ; perimeter
G1 X94.241 Y96.241 E11.84115 ; perimeter
G1 Z5.700 F6000.000 ; move to next layer (56)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X96.020 Y96.241 F6000.000 E11.85276 ; perimeter
G1 X102.078 Y100.420 E11.90082 ; perimeter
G1 X105.417 Y103.759 E11.93165 ; perimeter
G1 X94.241 Y103.759 E12.00462 ; perimeter
G1 X94.241 Y96.311 E12.05325 ; perimeter
G1 X94.241 Y96.241 E12.05370 ; perimeter
G1 Z5.800 F6000.000 ; move to next layer (57)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X96.050 Y96.241 F6000.000 E12.06550 ; perimeter
G1 X102.011 Y100.353 E12.11279 ; perimeter
G1 X105.417 Y103.759 E12.14424 ; perimeter
G1 X94.241 Y103.759 E12.21721 ; perimeter
G1 X94.241 Y96.311 E12.26584 ; perimeter
G1 X94.241 Y96.241 E12.26629 ; perimeter
G1 Z5.900 F6000.000 ; move to next layer (58)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X96.080 Y96.241 F6000.000 E12.27829 ; perimeter
G1 X101.945 Y100.286 E12.32481 ; perimeter
G1 X105.417 Y103.759 E12.35687 ; perimeter
G1 X94.241 Y103.759 E12.42984 ; perimeter
G1 X94.241 Y96.311 E12.47847 ; perimeter
G1 X94.241 Y96.241 E12.47893 ; perimeter
G1 Z6.000 F6000.000 ; move to next layer (59)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X96.110 Y96.241 F6000.000 E12.49112 ; perimeter
G1 X101.878 Y100.220 E12.53688 ; perimeter
G1 X105.417 Y103.759 E12.56955 ; perimeter
G1 X94.241 Y103.759 E12.64252 ; perimeter
G1 X94.241 Y96.311 E12.69115 ; perimeter
G1 X94.241 Y96.241 E12.69161 ; perimeter
G1 Z6.100 F6000.000 ; move to next layer (60)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X96.140 Y96.241 F6000.000 E12.70400 ; perimeter
G1 X101.811 Y100.153 E12.74899 ; perimeter
G1 X105.417 Y103.759 E12.78228 ; perimeter
G1 X94.241 Y103.759 E12.85525 ; perimeter
G1 X94.241 Y96.311 E12.90388 ; perimeter
G1 X94.241 Y96.241 E12.90433 ; perimeter
G1 Z6.200 F6000.000 ; move to next layer (61)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X96.170 Y96.241 F6000.000 E12.91692 ; perimeter
G1 X101.745 Y100.086 E12.96114 ; perimeter
G1 X105.417 Y103.759 E12.99505 ; perimeter
G1 X94.241 Y103.759 E13.06802 ; perimeter
G1 X94.241 Y96.311 E13.11665 ; perimeter
G1 X94.241 Y96.241 E13.11710 ; perimeter
G1 Z6.300 F6000.000 ; move to next layer (62)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X96.200 Y96.241 F6000.000 E13.12989 ; perimeter
G1 X101.678 Y100.020 E13.17334 ; perimeter
G1 X105.417 Y103.759 E13.20787 ; perimeter
G1 X94.241 Y103.759 E13.28084 ; perimeter
G1 X94.241 Y96.311 E13.32947 ; perimeter
G1 X94.241 Y96.241 E13.32992 ; perimeter
G1 Z6.400 F6000.000 ; move to next layer (63)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X96.230 Y96.241 F6000.000 E13.34290 ; perimeter
G1 X101.611 Y99.953 E13.38559 ; perimeter
G1 X105.417 Y103.759 E13.42073 ; perimeter
G1 X94.241 Y103.759 E13.49370 ; perimeter
G1 X94.241 Y96.311 E13.54232 ; perimeter
G1 X94.241 Y96.241 E13.54278 ; perimeter
G1 Z6.500 F6000.000 ; move to next layer (64)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X96.260 Y96.241 F6000.000 E13.55596 ; perimeter
G1 X101.545 Y99.886 E13.59787 ; perimeter
G1 X105.417 Y103.759 E13.63363 ; perimeter
G1 X94.241 Y103.759 E13.70660 ; perimeter
G1 X94.241 Y96.311 E13.75523 ; perimeter
G1 X94.241 Y96.241 E13.75568 ; perimeter
G1 Z6.600 F6000.000 ; move to next layer (65)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X96.290 Y96.241 F6000.000 E13.76906 ; perimeter
G1 X101.478 Y99.820 E13.81021 ; perimeter
G1 X105.417 Y103.759 E13.84658 ; perimeter
G1 X94.241 Y103.759 E13.91955 ; perimeter
G1 X94.241 Y96.311 E13.96818 ; perimeter
G1 X94.241 Y96.241 E13.96863 ; perimeter
G1 Z6.700 F6000.000 ; move to next layer (66)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X96.320 Y96.241 F6000.000 E13.98220 ; perimeter
G1 X101.411 Y99.753 E14.02259 ; perimeter
G1 X105.417 Y103.759 E14.05957 ; perimeter
G1 X94.241 Y103.759 E14.13254 ; perimeter
G1 X94.241 Y96.311 E14.18117 ; perimeter
G1 X94.241 Y96.241 E14.18163 ; perimeter
G1 Z6.800 F6000.000 ; move to next layer (67)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X96.350 Y96.241 F6000.000 E14.19539 ; perimeter
G1 X101.345 Y99.686 E14.23501 ; perimeter
G1 X105.417 Y103.759 E14.27261 ; perimeter
G1 X94.241 Y103.759 E14.34558 ; perimeter
G1 X94.241 Y96.311 E14.39421 ; perimeter
G1 X94.241 Y96.241 E14.39466 ; perimeter
G1 Z6.900 F6000.000 ; move to next layer (68)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X96.380 Y96.241 F6000.000 E14.40863 ; perimeter
G1 X101.278 Y99.620 E14.44748 ; perimeter
G1 X105.417 Y103.759 E14.48570 ; perimeter
G1 X94.241 Y103.759 E14.55867 ; perimeter
G1 X94.241 Y96.311 E14.60730 ; perimeter
G1 X94.241 Y96.241 E14.60775 ; perimeter
G1 Z7.000 F6000.000 ; move to next layer (69)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X96.410 Y96.241 F6000.000 E14.62191 ; perimeter
G1 X101.211 Y99.553 E14.65999 ; perimeter
G1 X105.417 Y103.759 E14.69882 ; perimeter
G1 X94.241 Y103.759 E14.77179 ; perimeter
G1 X94.241 Y96.311 E14.82042 ; perimeter
G1 X94.241 Y96.241 E14.82088 ; perimeter
G1 Z7.100 F6000.000 ; move to next layer (70)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X96.440 Y96.241 F6000.000 E14.83523 ; perimeter
G1 X101.145 Y99.486 E14.87255 ; perimeter
G1 X105.417 Y103.759 E14.91200 ; perimeter
G1 X94.241 Y103.759 E14.98497 ; perimeter
G1 X94.241 Y96.311 E15.03360 ; perimeter
G1 X94.241 Y96.241 E15.03405 ; perimeter
G1 Z7.200 F6000.000 ; move to next layer (71)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X96.470 Y96.241 F6000.000 E15.04860 ; perimeter
G1 X101.078 Y99.420 E15.08515 ; perimeter
G1 X105.417 Y103.759 E15.12522 ; perimeter
G1 X94.241 Y103.759 E15.19819 ; perimeter
G1 X94.241 Y96.311 E15.24682 ; perimeter
G1 X94.241 Y96.241 E15.24727 ; perimeter
G1 Z7.300 F6000.000 ; move to next layer (72)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X96.500 Y96.241 F6000.000 E15.26201 ; perimeter
G1 X101.011 Y99.353 E15.29780 ; perimeter
G1 X105.417 Y103.759 E15.33848 ; perimeter
G1 X94.241 Y103.759 E15.41145 ; perimeter
G1 X94.241 Y96.311 E15.46008 ; perimeter
G1 X94.241 Y96.241 E15.46053 ; perimeter
G1 Z7.400 F6000.000 ; move to next layer (73)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X96.530 Y96.241 F6000.000 E15.47547 ; perimeter
G1 X100.945 Y99.286 E15.51049 ; perimeter
G1 X105.417 Y103.759 E15.55179 ; perimeter
G1 X94.241 Y103.759 E15.62476 ; perimeter
G1 X94.241 Y96.311 E15.67339 ; perimeter
G1 X94.241 Y96.241 E15.67384 ; perimeter
G1 Z7.500 F6000.000 ; move to next layer (74)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X96.560 Y96.241 F6000.000 E15.68897 ; perimeter
G1 X100.878 Y99.220 E15.72323 ; perimeter
G1 X105.417 Y103.759 E15.76514 ; perimeter
G1 X94.241 Y103.759 E15.83811 ; perimeter
G1 X94.241 Y96.311 E15.88674 ; perimeter
G1 X94.241 Y96.241 E15.88719 ; perimeter
G1 Z7.600 F6000.000 ; move to next layer (75)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X96.590 Y96.241 F6000.000 E15.90252 ; perimeter
G1 X100.811 Y99.153 E15.93601 ; perimeter
G1 X105.417 Y103.759 E15.97853 ; perimeter
G1 X94.241 Y103.759 E16.05150 ; perimeter
G1 X94.241 Y96.311 E16.10013 ; perimeter
G1 X94.241 Y96.241 E16.10059 ; perimeter
G1 Z7.700 F6000.000 ; move to next layer (76)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X96.620 Y96.241 F6000.000 E16.11612 ; perimeter
G1 X100.745 Y99.086 E16.14883 ; perimeter
G1 X105.417 Y103.759 E16.19198 ; perimeter
G1 X94.241 Y103.759 E16.26495 ; perimeter
G1 X94.241 Y96.311 E16.31358 ; perimeter
G1 X94.241 Y96.241 E16.31403 ; perimeter
G1 Z7.800 F6000.000 ; move to next layer (77)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X96.650 Y96.241 F6000.000 E16.32975 ; perimeter
G1 X100.678 Y99.020 E16.36170 ; perimeter
G1 X105.417 Y103.759 E16.40546 ; perimeter
G1 X94.241 Y103.759 E16.47843 ; perimeter
G1 X94.241 Y96.311 E16.52706 ; perimeter
G1 X94.241 Y96.241 E16.52751 ; perimeter
G1 Z7.900 F6000.000 ; move to next layer (78)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X96.680 Y96.241 F6000.000 E16.54344 ; perimeter
G1 X100.611 Y98.953 E16.57462 ; perimeter
G1 X105.417 Y103.759 E16.61899 ; perimeter
G1 X94.241 Y103.759 E16.69196 ; perimeter
G1 X94.241 Y96.311 E16.74059 ; perimeter
G1 X94.241 Y96.241 E16.74105 ; perimeter
G1 Z8.000 F6000.000 ; move to next layer (79)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X96.710 Y96.241 F6000.000 E16.75716 ; perimeter
G1 X100.545 Y98.886 E16.78758 ; perimeter
G1 X105.417 Y103.759 E16.83257 ; perimeter
G1 X94.241 Y103.759 E16.90554 ; perimeter
G1 X94.241 Y96.311 E16.95417 ; perimeter
G1 X94.241 Y96.241 E16.95462 ; perimeter
G1 Z8.100 F6000.000 ; move to next layer (80)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X96.740 Y96.241 F6000.000 E16.97093 ; perimeter
G1 X100.478 Y98.820 E17.00059 ; perimeter
G1 X105.417 Y103.759 E17.04619 ; perimeter
G1 X94.241 Y103.759 E17.11916 ; perimeter
G1 X94.241 Y96.311 E17.16779 ; perimeter
G1 X94.241 Y96.241 E17.16824 ; perimeter
G1 Z8.200 F6000.000 ; move to next layer (81)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X96.770 Y96.241 F6000.000 E17.18475 ; perimeter
G1 X100.411 Y98.753 E17.21364 ; perimeter
G1 X105.417 Y103.759 E17.25986 ; perimeter
G1 X94.241 Y103.759 E17.33283 ; perimeter
G1 X94.241 Y96.311 E17.38146 ; perimeter
G1 X94.241 Y96.241 E17.38191 ; perimeter
G1 Z8.300 F6000.000 ; move to next layer (82)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X96.800 Y96.241 F6000.000 E17.39861 ; perimeter
G1 X100.345 Y98.686 E17.42673 ; perimeter
G1 X105.417 Y103.759 E17.47357 ; perimeter
G1 X94.241 Y103.759 E17.54654 ; perimeter
G1 X94.241 Y96.311 E17.59517 ; perimeter
G1 X94.241 Y96.241 E17.59562 ; perimeter
G1 Z8.400 F6000.000 ; move to next layer (83)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X96.830 Y96.241 F6000.000 E17.61252 ; perimeter
G1 X100.278 Y98.620 E17.63987 ; perimeter
G1 X105.417 Y103.759 E17.68732 ; perimeter
G1 X94.241 Y103.759 E17.76029 ; perimeter
G1 X94.241 Y96.311 E17.80892 ; perimeter
G1 X94.241 Y96.241 E17.80937 ; perimeter
G1 Z8.500 F6000.000 ; move to next layer (84)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X96.860 Y96.241 F6000.000 E17.82647 ; perimeter
G1 X100.211 Y98.553 E17.85305 ; perimeter
G1 X105.417 Y103.759 E17.90112 ; perimeter
G1 X94.241 Y103.759 E17.97409 ; perimeter
G1 X94.241 Y96.311 E18.02272 ; perimeter
G1 X94.241 Y96.241 E18.02317 ; perimeter
G1 Z8.600 F6000.000 ; move to next layer (85)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X96.890 Y96.241 F6000.000 E18.04047 ; perimeter
G1 X100.145 Y98.486 E18.06628 ; perimeter
G1 X105.417 Y103.759 E18.11497 ; perimeter
G1 X94.241 Y103.759 E18.18794 ; perimeter
G1 X94.241 Y96.311 E18.23657 ; perimeter
G1 X94.241 Y96.241 E18.23702 ; perimeter
G1 Z8.700 F6000.000 ; move to next layer (86)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X96.920 Y96.241 F6000.000 E18.25451 ; perimeter
G1 X100.078 Y98.420 E18.27956 ; perimeter
G1 X105.417 Y103.759 E18.32886 ; perimeter
G1 X94.241 Y103.759 E18.40183 ; perimeter
G1 X94.241 Y96.311 E18.45046 ; perimeter
G1 X94.241 Y96.241 E18.45091 ; perimeter
G1 Z8.800 F6000.000 ; move to next layer (87)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X96.950 Y96.241 F6000.000 E18.46859 ; perimeter
G1 X100.011 Y98.353 E18.49287 ; perimeter
G1 X105.417 Y103.759 E18.54279 ; perimeter
G1 X94.241 Y103.759 E18.61576 ; perimeter
G1 X94.241 Y96.311 E18.66439 ; perimeter
G1 X94.241 Y96.241 E18.66484 ; perimeter
G1 Z8.900 F6000.000 ; move to next layer (88)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X96.980 Y96.241 F6000.000 E18.68272 ; perimeter
G1 X99.945 Y98.286 E18.70624 ; perimeter
G1 X105.417 Y103.759 E18.75677 ; perimeter
G1 X94.241 Y103.759 E18.82974 ; perimeter
G1 X94.241 Y96.311 E18.87837 ; perimeter
G1 X94.241 Y96.241 E18.87882 ; perimeter
G1 Z9.000 F6000.000 ; move to next layer (89)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X97.010 Y96.241 F6000.000 E18.89690 ; perimeter
G1 X99.878 Y98.220 E18.91965 ; perimeter
G1 X105.417 Y103.759 E18.97079 ; perimeter
G1 X94.241 Y103.759 E19.04376 ; perimeter
G1 X94.241 Y96.311 E19.09239 ; perimeter
G1 X94.241 Y96.241 E19.09284 ; perimeter
G1 Z9.100 F6000.000 ; move to next layer (90)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X97.040 Y96.241 F6000.000 E19.11112 ; perimeter
G1 X99.811 Y98.153 E19.13310 ; perimeter
G1 X105.417 Y103.759 E19.18486 ; perimeter
G1 X94.241 Y103.759 E19.25783 ; perimeter
G1 X94.241 Y96.311 E19.30646 ; perimeter
G1 X94.241 Y96.241 E19.30691 ; perimeter
G1 Z9.200 F6000.000 ; move to next layer (91)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X97.070 Y96.241 F6000.000 E19.32538 ; perimeter
G1 X99.745 Y98.086 E19.34660 ; perimeter
G1 X105.417 Y103.759 E19.39897 ; perimeter
G1 X94.241 Y103.759 E19.47194 ; perimeter
G1 X94.241 Y96.311 E19.52057 ; perimeter
G1 X94.241 Y96.241 E19.52103 ; perimeter
G1 Z9.300 F6000.000 ; move to next layer (92)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X97.100 Y96.241 F6000.000 E19.53969 ; perimeter
G1 X99.678 Y98.020 E19.56014 ; perimeter
G1 X105.417 Y103.759 E19.61313 ; perimeter
G1 X94.241 Y103.759 E19.68610 ; perimeter
G1 X94.241 Y96.311 E19.73473 ; perimeter
G1 X94.241 Y96.241 E19.73518 ; perimeter
G1 Z9.400 F6000.000 ; move to next layer (93)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X97.130 Y96.241 F6000.000 E19.75404 ; perimeter
G1 X99.611 Y97.953 E19.77373 ; perimeter
G1 X105.417 Y103.759 E19.82733 ; perimeter
G1 X94.241 Y103.759 E19.90030 ; perimeter
G1 X94.241 Y96.311 E19.94893 ; perimeter
G1 X94.241 Y96.241 E19.94939 ; perimeter
G1 Z9.500 F6000.000 ; move to next layer (94)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X97.160 Y96.241 F6000.000 E19.96844 ; perimeter
G1 X99.545 Y97.886 E19.98736 ; perimeter
G1 X105.417 Y103.759 E20.04158 ; perimeter
G1 X94.241 Y103.759 E20.11455 ; perimeter
G1 X94.241 Y96.311 E20.16318 ; perimeter
G1 X94.241 Y96.241 E20.16363 ; perimeter
G1 Z9.600 F6000.000 ; move to next layer (95)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X97.190 Y96.241 F6000.000 E20.18288 ; perimeter
G1 X99.478 Y97.820 E20.20103 ; perimeter
G1 X105.417 Y103.759 E20.25587 ; perimeter
G1 X94.241 Y103.759 E20.32884 ; perimeter
G1 X94.241 Y96.311 E20.37747 ; perimeter
G1 X94.241 Y96.241 E20.37793 ; perimeter
G1 Z9.700 F6000.000 ; move to next layer (96)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X97.220 Y96.241 F6000.000 E20.39737 ; perimeter
G1 X99.411 Y97.753 E20.41476 ; perimeter
G1 X105.417 Y103.759 E20.47021 ; perimeter
G1 X94.241 Y103.759 E20.54318 ; perimeter
G1 X94.241 Y96.311 E20.59181 ; perimeter
G1 X94.241 Y96.241 E20.59226 ; perimeter
G1 Z9.800 F6000.000 ; move to next layer (97)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X97.250 Y96.241 F6000.000 E20.61190 ; perimeter
G1 X99.345 Y97.686 E20.62852 ; perimeter
G1 X105.417 Y103.759 E20.68459 ; perimeter
G1 X94.241 Y103.759 E20.75756 ; perimeter
G1 X94.241 Y96.311 E20.80619 ; perimeter
G1 X94.241 Y96.241 E20.80664 ; perimeter
G1 Z9.900 F6000.000 ; move to next layer (98)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X97.280 Y96.241 F6000.000 E20.82648 ; perimeter
G1 X99.278 Y97.620 E20.84233 ; perimeter
G1 X105.417 Y103.759 E20.89902 ; perimeter
G1 X94.241 Y103.759 E20.97199 ; perimeter
G1 X94.241 Y96.311 E21.02062 ; perimeter
G1 X94.241 Y96.241 E21.02107 ; perimeter
G1 Z10.000 F6000.000 ; move to next layer (99)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X97.310 Y96.241 F6000.000 E21.04110 ; perimeter
G1 X99.211 Y97.553 E21.05619 ; perimeter
G1 X105.417 Y103.759 E21.11349 ; perimeter
G1 X94.241 Y103.759 E21.18646 ; perimeter
G1 X94.241 Y96.311 E21.23509 ; perimeter
G1 X94.241 Y96.241 E21.23554 ; perimeter
G1 Z10.100 F6000.000 ; move to next layer (100)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X97.340 Y96.241 F6000.000 E21.25577 ; perimeter
G1 X99.145 Y97.486 E21.27009 ; perimeter
G1 X105.417 Y103.759 E21.32801 ; perimeter
G1 X94.241 Y103.759 E21.40098 ; perimeter
G1 X94.241 Y96.311 E21.44961 ; perimeter
G1 X94.241 Y96.241 E21.45006 ; perimeter
G1 Z10.200 F6000.000 ; move to next layer (101)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X97.370 Y96.241 F6000.000 E21.47048 ; perimeter
G1 X99.078 Y97.420 E21.48403 ; perimeter
G1 X105.417 Y103.759 E21.54257 ; perimeter
G1 X94.241 Y103.759 E21.61554 ; perimeter
G1 X94.241 Y96.311 E21.66417 ; perimeter
G1 X94.241 Y96.241 E21.66462 ; perimeter
G1 Z10.300 F6000.000 ; move to next layer (102)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X97.400 Y96.241 F6000.000 E21.68524 ; perimeter
G1 X99.011 Y97.353 E21.69802 ; perimeter
G1 X105.417 Y103.759 E21.75717 ; perimeter
G1 X94.241 Y103.759 E21.83014 ; perimeter
G1 X94.241 Y96.311 E21.87877 ; perimeter
G1 X94.241 Y96.241 E21.87922 ; perimeter
G1 Z10.400 F6000.000 ; move to next layer (103)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X97.430 Y96.241 F6000.000 E21.90004 ; perimeter
G1 X98.945 Y97.286 E21.91206 ; perimeter
G1 X105.417 Y103.759 E21.97182 ; perimeter
G1 X94.241 Y103.759 E22.04479 ; perimeter
G1 X94.241 Y96.311 E22.09342 ; perimeter
G1 X94.241 Y96.241 E22.09387 ; perimeter
G1 Z10.500 F6000.000 ; move to next layer (104)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X97.460 Y96.241 F6000.000 E22.11489 ; perimeter
G1 X98.878 Y97.220 E22.12614 ; perimeter
G1 X105.417 Y103.759 E22.18652 ; perimeter
G1 X94.241 Y103.759 E22.25949 ; perimeter
G1 X94.241 Y96.311 E22.30812 ; perimeter
G1 X94.241 Y96.241 E22.30857 ; perimeter
G1 Z10.600 F6000.000 ; move to next layer (105)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X97.490 Y96.241 F6000.000 E22.32978 ; perimeter
G1 X98.811 Y97.153 E22.34026 ; perimeter
G1 X105.417 Y103.759 E22.40126 ; perimeter
G1 X94.241 Y103.759 E22.47423 ; perimeter
G1 X94.241 Y96.311 E22.52286 ; perimeter
G1 X94.241 Y96.241 E22.52331 ; perimeter
G1 Z10.700 F6000.000 ; move to next layer (106)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X97.520 Y96.241 F6000.000 E22.54471 ; perimeter
G1 X98.745 Y97.086 E22.55443 ; perimeter
G1 X105.417 Y103.759 E22.61604 ; perimeter
G1 X94.241 Y103.759 E22.68901 ; perimeter
G1 X94.241 Y96.311 E22.73764 ; perimeter
G1 X94.241 Y96.241 E22.73809 ; perimeter
G1 Z10.800 F6000.000 ; move to next layer (107)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X97.550 Y96.241 F6000.000 E22.75969 ; perimeter
G1 X98.678 Y97.020 E22.76864 ; perimeter
G1 X105.417 Y103.759 E22.83087 ; perimeter
G1 X94.241 Y103.759 E22.90384 ; perimeter
G1 X94.241 Y96.311 E22.95247 ; perimeter
G1 X94.241 Y96.241 E22.95292 ; perimeter
G1 Z10.900 F6000.000 ; move to next layer (108)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X97.580 Y96.241 F6000.000 E22.97472 ; perimeter
G1 X98.611 Y96.953 E22.98290 ; perimeter
G1 X105.417 Y103.759 E23.04574 ; perimeter
G1 X94.241 Y103.759 E23.11871 ; perimeter
G1 X94.241 Y96.311 E23.16734 ; perimeter
G1 X94.241 Y96.241 E23.16780 ; perimeter
G1 Z11.000 F6000.000 ; move to next layer (109)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X97.610 Y96.241 F6000.000 E23.18979 ; perimeter
G1 X98.545 Y96.886 E23.19720 ; perimeter
G1 X105.417 Y103.759 E23.26066 ; perimeter
G1 X94.241 Y103.759 E23.33363 ; perimeter
G1 X94.241 Y96.311 E23.38226 ; perimeter
G1 X94.241 Y96.241 E23.38271 ; perimeter
G1 Z11.100 F6000.000 ; move to next layer (110)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X97.640 Y96.241 F6000.000 E23.40490 ; perimeter
G1 X98.478 Y96.820 E23.41155 ; perimeter
G1 X105.417 Y103.759 E23.47563 ; perimeter
G1 X94.241 Y103.759 E23.54860 ; perimeter
G1 X94.241 Y96.311 E23.59723 ; perimeter
G1 X94.241 Y96.241 E23.59768 ; perimeter
G1 Z11.200 F6000.000 ; move to next layer (111)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X97.670 Y96.241 F6000.000 E23.62006 ; perimeter
G1 X98.411 Y96.753 E23.62595 ; perimeter
G1 X105.417 Y103.759 E23.69063 ; perimeter
G1 X94.241 Y103.759 E23.76360 ; perimeter
G1 X94.241 Y96.311 E23.81223 ; perimeter
G1 X94.241 Y96.241 E23.81269 ; perimeter
G1 Z11.300 F6000.000 ; move to next layer (112)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X97.700 Y96.241 F6000.000 E23.83527 ; perimeter
G1 X98.345 Y96.686 E23.84038 ; perimeter
G1 X105.417 Y103.759 E23.90569 ; perimeter
G1 X94.241 Y103.759 E23.97866 ; perimeter
G1 X94.241 Y96.311 E24.02729 ; perimeter
G1 X94.241 Y96.241 E24.02774 ; perimeter
G1 Z11.400 F6000.000 ; move to next layer (113)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X97.730 Y96.241 F6000.000 E24.05052 ; perimeter
G1 X98.278 Y96.620 E24.05487 ; perimeter
G1 X105.417 Y103.759 E24.12079 ; perimeter
G1 X94.241 Y103.759 E24.19376 ; perimeter
G1 X94.241 Y96.311 E24.24239 ; perimeter
G1 X94.241 Y96.241 E24.24284 ; perimeter
G1 Z11.500 F6000.000 ; move to next layer (114)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X97.760 Y96.241 F6000.000 E24.26581 ; perimeter
G1 X98.211 Y96.553 E24.26939 ; perimeter
G1 X105.417 Y103.759 E24.33593 ; perimeter
G1 X94.241 Y103.759 E24.40890 ; perimeter
G1 X94.241 Y96.311 E24.45753 ; perimeter
G1 X94.241 Y96.241 E24.45798 ; perimeter
G1 Z11.600 F6000.000 ; move to next layer (115)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X97.790 Y96.241 F6000.000 E24.48115 ; perimeter
G1 X98.145 Y96.486 E24.48396 ; perimeter
G1 X105.417 Y103.759 E24.55112 ; perimeter
G1 X94.241 Y103.759 E24.62409 ; perimeter
G1 X94.241 Y96.311 E24.67271 ; perimeter
G1 X94.241 Y96.241 E24.67317 ; perimeter
G1 Z11.700 F6000.000 ; move to next layer (116)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X97.820 Y96.241 F6000.000 E24.69653 ; perimeter
G1 X98.078 Y96.420 E24.69858 ; perimeter
G1 X105.417 Y103.759 E24.76635 ; perimeter
G1 X94.241 Y103.759 E24.83932 ; perimeter
G1 X94.241 Y96.311 E24.88795 ; perimeter
G1 X94.241 Y96.241 E24.88840 ; perimeter
G1 Z11.800 F6000.000 ; move to next layer (117)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X97.850 Y96.241 F6000.000 E24.91196 ; perimeter
G1 X98.011 Y96.353 E24.91324 ; perimeter
G1 X105.417 Y103.759 E24.98162 ; perimeter
G1 X94.241 Y103.759 E25.05459 ; perimeter
G1 X94.241 Y96.311 E25.10322 ; perimeter
G1 X94.241 Y96.241 E25.10368 ; perimeter
G1 Z11.900 F6000.000 ; move to next layer (118)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X97.900 Y96.241 F6000.000 E25.12756 ; perimeter
G1 X105.417 Y103.759 E25.19698 ; perimeter
G1 X94.241 Y103.759 E25.26995 ; perimeter
G1 X94.241 Y96.311 E25.31858 ; perimeter
G1 X94.241 Y96.241 E25.31903 ; perimeter
G1 Z12.000 F6000.000 ; move to next layer (119)
G1 X94.241 Y96.241 ; move to first perimeter point
G1 X97.900 Y96.241 F6000.000 E25.34292 ; perimeter
G1 X105.417 Y103.759 E25.41233 ; perimeter
G1 X94.241 Y103.759 E25.48530 ; perimeter
G1 X94.241 Y96.311 E25.53393 ; perimeter
G1 X94.241 Y96.241 E25.53438 ; perimeter

; filament used = 25.5mm (0.2cm3)

; acceleration = 0
; bed_size = 200,200
; bed_temperature = 0
; bottom_solid_layers = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 1.16
; bridge_speed = 100
; brim_width = 0
; complete_objects = 
; cooling = 
; disable_fan_first_layers = 0
; duplicate = 1
; duplicate_distance = 6
; duplicate_grid = 1,1
; end_gcode = 
; external_perimeter_speed = 100
; extra_perimeters = 
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0
; fan_always_on = 
; fan_below_layer_time = 0
; filament_diameter = 3
; fill_angle = 45
; fill_density = 0
; fill_pattern = rectilinear
; first_layer_bed_temperature = 0
; first_layer_extrusion_width = 0
; first_layer_height = 100%
; first_layer_speed = 100
; first_layer_temperature = 0
; g0 = 0
; gap_fill_speed = 20
; gcode_arcs = 0
; gcode_comments = 1
; gcode_flavor = reprap
; infill_acceleration = 50
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0
; infill_speed = 100
; layer_gcode = 
; layer_height = .1
; max_fan_speed = 100
; min_fan_speed = 100
; min_print_speed = 1
; min_skirt_length = 0
; notes = This config has a workaround for the extrusion retraction compensation bug for the first layer... be sure to comment out those 3 lines IF the bug has been fixed.
; nozzle_diameter = .345
; only_retract_when_crossing_perimeters = 1
; output_filename_format = [input_filename_base]_[timestamp].gcode
; perimeter_acceleration = 25
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_speed = 100
; perimeters = 1
; post_process = 
; print_center = 100,100
; randomize_start = 
; retract_before_travel = 0
; retract_length = 0
; retract_length_toolchange = 0
; retract_lift = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 26
; rotate = 0
; scale = 1
; skirt_distance = 0
; skirt_height = 0
; skirts = 0
; slowdown_below_layer_time = 0
; small_perimeter_speed = 100
; solid_fill_pattern = rectilinear
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_speed = 100
; start_gcode = G92 E0\nG1 E100\nG1 E0
; support_material = 
; support_material_angle = 45
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_pattern = honeycomb
; support_material_spacing = 0
; support_material_speed = 60
; support_material_threshold = 0
; temperature = 0,0,0
; threads = 4
; top_solid_infill_speed = 100
; top_solid_layers = 0
; travel_speed = 100
; use_relative_e_distances = 0
; vibration_limit = 0
; z_offset = 0
