; generated by Slic3r 0.9.6-dev on 2012-11-19 at 09:02:17

; This config has a workaround for the extrusion retraction compensation bug for the first layer... be sure to comment out those 3 lines IF the bug has been fixed.

; layer_height = .175
; perimeters = 1
; top_solid_layers = 0
; bottom_solid_layers = 0
; fill_density = 0
; perimeter_speed = 130
; infill_speed = 130
; travel_speed = 300
; scale = 1
; nozzle_diameter = .345
; filament_diameter = 2.9
; extrusion_multiplier = 1
; perimeters extrusion width = 0.48mm
; infill extrusion width = 0.48mm
; first layer extrusion width = 0.48mm

G90 ; use absolute coordinates
G21 ; set units to millimeters
M82 ; use absolute distances for extrusion
G28 ; go home and zero the axes
G92 X0 Y0 Z0 E0.0
G1 Z1.0 F240 ; Head on up to a location I can be seen.
G1 E5 ; let's spew a little.
G92 E2.0
G1 E0.0 ; retract a little so I stop drooling.
G1 X0 Y0 Z0 F3000
G1 Y30
G1 X30 
G1 Y0 
G1 X100 Y0 Z1.0
G1 X100 Y30 Z0 E3
G92 E0
M106
G90 ; use absolute coordinates
G21 ; set units to millimeters
G92 E0 ; reset extrusion distance
M82 ; use absolute distances for extrusion
M106 S255 ; enable fan
G1 F1560.000 E-1.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z0.480 F18000.000 ; move to next layer (0)
G1 X97.241 Y98.469 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X97.380 Y98.397 F3000.000 E1.00214 ; perimeter
G1 X101.909 Y101.520 E1.07767 ; perimeter
G1 X101.834 Y101.759 E1.08110 ; perimeter
G1 X97.241 Y101.759 E1.14415 ; perimeter
G1 X97.241 Y98.537 E1.18837 ; perimeter
G1 X97.241 Y98.469 E1.18930 ; perimeter
G1 F1560.000 E0.18930 ; retract
G92 E0 ; reset extrusion distance
G1 X102.506 Y101.849 F18000.000 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X102.704 Y101.923 F3000.000 E1.00290 ; perimeter
G1 X102.311 Y101.780 F18000.000 ; move to first perimeter point
G1 X102.506 Y101.849 F3000.000 E1.00574 ; perimeter
G1 X102.305 Y101.774 F18000.000 ; move to first perimeter point
G1 X102.308 Y101.784 F3000.000 E1.00588 ; perimeter
G1 X100.819 Y101.495 F18000.000 ; move to first fill point
G1 X100.651 Y101.327 F3000.000 E1.00793 ; fill
G1 X101.223 Y101.495 F18000.000 ; move to first fill point
G1 X101.054 Y101.327 F3000.000 E1.00999 ; fill
G1 F1560.000 E0.00999 ; retract
G92 E0 ; reset extrusion distance
G1 X97.673 Y99.070 F18000.000 ; move to first fill point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X97.505 Y98.902 F3000.000 E1.00190 ; fill
G1 F1560.000 E0.00190 ; retract
G92 E0 ; reset extrusion distance
G1 Z0.655 F18000.000 ; move to next layer (1)
G1 X97.241 Y98.430 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X97.380 Y98.358 F3000.000 E1.00188 ; perimeter
G1 X101.965 Y101.520 E1.06878 ; perimeter
G1 X101.891 Y101.759 E1.07178 ; perimeter
G1 X97.241 Y101.759 E1.12763 ; perimeter
G1 X97.241 Y98.499 E1.16679 ; perimeter
G1 X97.241 Y98.430 E1.16760 ; perimeter
G1 F1560.000 E0.16760 ; retract
G92 E0 ; reset extrusion distance
G1 X102.638 Y101.856 F18000.000 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X102.651 Y101.875 F3000.000 E1.00027 ; perimeter
G1 X102.361 Y101.773 F18000.000 ; move to first perimeter point
G1 X102.638 Y101.856 F3000.000 E1.00374 ; perimeter
G1 X102.360 Y101.774 F18000.000 ; move to first perimeter point
G1 X102.361 Y101.773 F3000.000 E1.00376 ; perimeter
G1 X101.279 Y101.327 F18000.000 ; move to first fill point
G1 X101.111 Y101.495 F3000.000 E1.00626 ; fill
G1 X100.947 Y101.098 F18000.000 ; move to first fill point
G1 X100.779 Y101.266 F3000.000 E1.00876 ; fill
G1 F1560.000 E0.00876 ; retract
G92 E0 ; reset extrusion distance
G1 X97.692 Y98.853 F18000.000 ; move to first fill point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X97.523 Y99.021 F3000.000 E1.00166 ; fill
G1 F1560.000 E0.00166 ; retract
G92 E0 ; reset extrusion distance
G1 Z0.830 F18000.000 ; move to next layer (2)
G1 X97.241 Y98.394 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X97.380 Y98.322 F3000.000 E1.00188 ; perimeter
G1 X102.017 Y101.520 E1.06955 ; perimeter
G1 X101.943 Y101.759 E1.07255 ; perimeter
G1 X97.241 Y101.759 E1.12902 ; perimeter
G1 X97.241 Y98.462 E1.16862 ; perimeter
G1 X97.241 Y98.394 E1.16943 ; perimeter
G1 F1560.000 E0.16943 ; retract
G92 E0 ; reset extrusion distance
G1 X102.670 Y101.865 F18000.000 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X102.674 Y101.864 F3000.000 E1.00004 ; perimeter
G1 X102.414 Y101.777 F18000.000 ; move to first perimeter point
G1 X102.670 Y101.865 F3000.000 E1.00330 ; perimeter
G1 X102.411 Y101.773 F18000.000 ; move to first perimeter point
G1 X102.414 Y101.777 F3000.000 E1.00335 ; perimeter
G1 X100.928 Y101.495 F18000.000 ; move to first fill point
G1 X100.760 Y101.327 F3000.000 E1.00515 ; fill
G1 X101.331 Y101.495 F18000.000 ; move to first fill point
G1 X101.163 Y101.327 F3000.000 E1.00695 ; fill
G1 F1560.000 E0.00695 ; retract
G92 E0 ; reset extrusion distance
G1 X97.673 Y98.995 F18000.000 ; move to first fill point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X97.505 Y98.827 F3000.000 E1.00166 ; fill
G1 F1560.000 E0.00166 ; retract
G92 E0 ; reset extrusion distance
G1 Z1.005 F18000.000 ; move to next layer (3)
G1 X97.241 Y98.358 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X97.380 Y98.285 F3000.000 E1.00188 ; perimeter
G1 X102.070 Y101.520 E1.07031 ; perimeter
G1 X101.996 Y101.759 E1.07331 ; perimeter
G1 X97.241 Y101.759 E1.13042 ; perimeter
G1 X97.241 Y98.426 E1.17045 ; perimeter
G1 X97.241 Y98.358 E1.17127 ; perimeter
G1 F1560.000 E0.17127 ; retract
G92 E0 ; reset extrusion distance
G1 X102.502 Y101.790 F18000.000 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X102.702 Y101.873 F3000.000 E1.00261 ; perimeter
G1 X102.459 Y101.772 F18000.000 ; move to first perimeter point
G1 X102.502 Y101.790 F3000.000 E1.00316 ; perimeter
G1 X102.442 Y101.649 F18000.000 ; move to first perimeter point
G1 X102.459 Y101.772 F3000.000 E1.00465 ; perimeter
G1 X101.384 Y101.327 F18000.000 ; move to first fill point
G1 X101.216 Y101.495 F3000.000 E1.00715 ; fill
G1 X101.052 Y101.098 F18000.000 ; move to first fill point
G1 X100.884 Y101.266 F3000.000 E1.00965 ; fill
G1 F1560.000 E0.00965 ; retract
G92 E0 ; reset extrusion distance
G1 X97.692 Y98.781 F18000.000 ; move to first fill point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X97.523 Y98.949 F3000.000 E1.00166 ; fill
G1 F1560.000 E0.00166 ; retract
G92 E0 ; reset extrusion distance
G1 Z1.180 F18000.000 ; move to next layer (4)
G1 X97.241 Y98.322 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X97.380 Y98.249 F3000.000 E1.00188 ; perimeter
G1 X102.122 Y101.520 E1.07108 ; perimeter
G1 X102.048 Y101.759 E1.07408 ; perimeter
G1 X97.241 Y101.759 E1.13182 ; perimeter
G1 X97.241 Y98.390 E1.17228 ; perimeter
G1 X97.241 Y98.322 E1.17310 ; perimeter
G1 F1560.000 E0.17310 ; retract
G92 E0 ; reset extrusion distance
G1 X102.696 Y101.867 F18000.000 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X102.710 Y101.891 F3000.000 E1.00033 ; perimeter
G1 X102.498 Y101.773 F18000.000 ; move to first perimeter point
G1 X102.696 Y101.867 F3000.000 E1.00296 ; perimeter
G1 X102.490 Y101.765 F18000.000 ; move to first perimeter point
G1 X102.498 Y101.773 F3000.000 E1.00309 ; perimeter
G1 X101.033 Y101.495 F18000.000 ; move to first fill point
G1 X100.865 Y101.327 F3000.000 E1.00489 ; fill
G1 X101.436 Y101.495 F18000.000 ; move to first fill point
G1 X101.268 Y101.327 F3000.000 E1.00668 ; fill
G1 F1560.000 E0.00668 ; retract
G92 E0 ; reset extrusion distance
G1 Z1.355 F18000.000 ; move to next layer (5)
G1 X102.175 Y101.520 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X102.101 Y101.759 F3000.000 E1.00300 ; perimeter
G1 X97.241 Y101.759 E1.06137 ; perimeter
G1 X97.241 Y98.286 E1.10308 ; perimeter
G1 X97.380 Y98.213 E1.10496 ; perimeter
G1 X102.119 Y101.481 E1.17411 ; perimeter
G1 X102.175 Y101.520 E1.17493 ; perimeter
G1 X101.489 Y101.327 F18000.000 ; move to first fill point
G1 X101.321 Y101.495 F3000.000 E1.17743 ; fill
G1 X101.157 Y101.098 F18000.000 ; move to first fill point
G1 X100.989 Y101.266 F3000.000 E1.17993 ; fill
G1 F1560.000 E0.17993 ; retract
G92 E0 ; reset extrusion distance
G1 X97.692 Y98.708 F18000.000 ; move to first fill point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X97.523 Y98.876 F3000.000 E1.00166 ; fill
G1 F1560.000 E0.00166 ; retract
G92 E0 ; reset extrusion distance
G1 Z1.530 F18000.000 ; move to next layer (6)
G1 X97.241 Y98.249 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X97.380 Y98.177 F3000.000 E1.00188 ; perimeter
G1 X102.227 Y101.520 E1.07261 ; perimeter
G1 X102.153 Y101.759 E1.07561 ; perimeter
G1 X97.241 Y101.759 E1.13461 ; perimeter
G1 X97.241 Y98.317 E1.17594 ; perimeter
G1 X97.241 Y98.249 E1.17676 ; perimeter
G1 F1560.000 E0.17676 ; retract
G92 E0 ; reset extrusion distance
G1 X101.138 Y101.495 F18000.000 ; move to first fill point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X100.970 Y101.327 F3000.000 E1.00180 ; fill
G1 X101.541 Y101.495 F18000.000 ; move to first fill point
G1 X101.373 Y101.327 F3000.000 E1.00360 ; fill
G1 F1560.000 E0.00360 ; retract
G92 E0 ; reset extrusion distance
G1 X97.673 Y98.850 F18000.000 ; move to first fill point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X97.505 Y98.682 F3000.000 E1.00166 ; fill
G1 F1560.000 E0.00166 ; retract
G92 E0 ; reset extrusion distance
G1 Z1.705 F18000.000 ; move to next layer (7)
G1 X97.241 Y98.213 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X97.380 Y98.141 F3000.000 E1.00188 ; perimeter
G1 X101.953 Y101.295 E1.06861 ; perimeter
G1 X102.233 Y101.574 E1.07336 ; perimeter
G1 X102.157 Y101.759 E1.07576 ; perimeter
G1 X97.241 Y101.759 E1.13480 ; perimeter
G1 X97.241 Y98.281 E1.17657 ; perimeter
G1 X97.241 Y98.213 E1.17738 ; perimeter
G1 F1560.000 E0.17738 ; retract
G92 E0 ; reset extrusion distance
G1 X101.594 Y101.327 F18000.000 ; move to first fill point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X101.426 Y101.495 F3000.000 E1.00250 ; fill
G1 X101.262 Y101.098 F18000.000 ; move to first fill point
G1 X101.094 Y101.266 F3000.000 E1.00500 ; fill
G1 F1560.000 E0.00500 ; retract
G92 E0 ; reset extrusion distance
G1 Z1.880 F18000.000 ; move to next layer (8)
G1 X101.836 Y101.178 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X102.233 Y101.574 F3000.000 E1.00673 ; perimeter
G1 X102.157 Y101.759 E1.00913 ; perimeter
G1 X97.241 Y101.759 E1.06817 ; perimeter
G1 X97.241 Y98.241 E1.11042 ; perimeter
G1 X97.579 Y98.241 E1.11446 ; perimeter
G1 X101.780 Y101.139 E1.17578 ; perimeter
G1 X101.836 Y101.178 E1.17659 ; perimeter
G1 X101.243 Y101.495 F18000.000 ; move to first fill point
G1 X101.075 Y101.327 F3000.000 E1.17839 ; fill
G1 X101.646 Y101.495 F18000.000 ; move to first fill point
G1 X101.478 Y101.327 F3000.000 E1.18019 ; fill
G1 F1560.000 E0.18019 ; retract
G92 E0 ; reset extrusion distance
G1 X97.673 Y98.777 F18000.000 ; move to first fill point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X97.505 Y98.609 F3000.000 E1.00166 ; fill
G1 F1560.000 E0.00166 ; retract
G92 E0 ; reset extrusion distance
G1 Z2.055 F18000.000 ; move to next layer (9)
G1 X97.631 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X101.720 Y101.061 F3000.000 E1.05966 ; perimeter
G1 X102.233 Y101.574 E1.06838 ; perimeter
G1 X102.157 Y101.759 E1.07077 ; perimeter
G1 X97.241 Y101.759 E1.12981 ; perimeter
G1 X97.241 Y98.241 E1.17206 ; perimeter
G1 X97.563 Y98.241 E1.17592 ; perimeter
G1 X97.631 Y98.241 E1.17674 ; perimeter
G1 F1560.000 E0.17674 ; retract
G92 E0 ; reset extrusion distance
G1 X101.662 Y101.327 F18000.000 ; move to first fill point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X101.494 Y101.495 F3000.000 E1.00233 ; fill
G1 X101.367 Y101.098 F18000.000 ; move to first fill point
G1 X101.199 Y101.266 F3000.000 E1.00467 ; fill
G1 F1560.000 E0.00467 ; retract
G92 E0 ; reset extrusion distance
G1 X97.692 Y98.563 F18000.000 ; move to first fill point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X97.523 Y98.732 F3000.000 E1.00166 ; fill
G1 F1560.000 E0.00166 ; retract
G92 E0 ; reset extrusion distance
G1 Z2.230 F18000.000 ; move to next layer (10)
G1 X97.684 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X101.603 Y100.945 F3000.000 E1.05719 ; perimeter
G1 X102.233 Y101.574 E1.06789 ; perimeter
G1 X102.157 Y101.759 E1.07029 ; perimeter
G1 X97.241 Y101.759 E1.12933 ; perimeter
G1 X97.241 Y98.241 E1.17157 ; perimeter
G1 X97.616 Y98.241 E1.17607 ; perimeter
G1 X97.684 Y98.241 E1.17688 ; perimeter
G1 F1560.000 E0.17688 ; retract
G92 E0 ; reset extrusion distance
G1 Z2.405 F18000.000 ; move to next layer (11)
G1 X97.736 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X101.486 Y100.828 F3000.000 E1.05472 ; perimeter
G1 X102.233 Y101.574 E1.06741 ; perimeter
G1 X102.157 Y101.759 E1.06980 ; perimeter
G1 X97.241 Y101.759 E1.12884 ; perimeter
G1 X97.241 Y98.241 E1.17109 ; perimeter
G1 X97.668 Y98.241 E1.17621 ; perimeter
G1 X97.736 Y98.241 E1.17703 ; perimeter
G1 F1560.000 E0.17703 ; retract
G92 E0 ; reset extrusion distance
G1 Z2.580 F18000.000 ; move to next layer (12)
G1 X97.789 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X101.370 Y100.711 F3000.000 E1.05226 ; perimeter
G1 X102.233 Y101.574 E1.06692 ; perimeter
G1 X102.157 Y101.759 E1.06931 ; perimeter
G1 X97.241 Y101.759 E1.12835 ; perimeter
G1 X97.241 Y98.241 E1.17060 ; perimeter
G1 X97.721 Y98.241 E1.17635 ; perimeter
G1 X97.789 Y98.241 E1.17717 ; perimeter
G1 F1560.000 E0.17717 ; retract
G92 E0 ; reset extrusion distance
G1 Z2.755 F18000.000 ; move to next layer (13)
G1 X97.841 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X101.253 Y100.595 F3000.000 E1.04979 ; perimeter
G1 X102.233 Y101.574 E1.06643 ; perimeter
G1 X102.157 Y101.759 E1.06883 ; perimeter
G1 X97.241 Y101.759 E1.12787 ; perimeter
G1 X97.241 Y98.241 E1.17011 ; perimeter
G1 X97.773 Y98.241 E1.17650 ; perimeter
G1 X97.841 Y98.241 E1.17732 ; perimeter
G1 F1560.000 E0.17732 ; retract
G92 E0 ; reset extrusion distance
G1 Z2.930 F18000.000 ; move to next layer (14)
G1 X97.894 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X101.136 Y100.478 F3000.000 E1.04732 ; perimeter
G1 X102.233 Y101.574 E1.06595 ; perimeter
G1 X102.157 Y101.759 E1.06834 ; perimeter
G1 X97.241 Y101.759 E1.12738 ; perimeter
G1 X97.241 Y98.241 E1.16963 ; perimeter
G1 X97.826 Y98.241 E1.17664 ; perimeter
G1 X97.894 Y98.241 E1.17746 ; perimeter
G1 F1560.000 E0.17746 ; retract
G92 E0 ; reset extrusion distance
G1 Z3.105 F18000.000 ; move to next layer (15)
G1 X97.946 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X101.020 Y100.361 F3000.000 E1.04485 ; perimeter
G1 X102.233 Y101.574 E1.06546 ; perimeter
G1 X102.157 Y101.759 E1.06785 ; perimeter
G1 X97.241 Y101.759 E1.12689 ; perimeter
G1 X97.241 Y98.241 E1.16914 ; perimeter
G1 X97.878 Y98.241 E1.17679 ; perimeter
G1 X97.946 Y98.241 E1.17760 ; perimeter
G1 F1560.000 E0.17760 ; retract
G92 E0 ; reset extrusion distance
G1 Z3.280 F18000.000 ; move to next layer (16)
G1 X97.999 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X100.903 Y100.245 F3000.000 E1.04238 ; perimeter
G1 X102.233 Y101.574 E1.06497 ; perimeter
G1 X102.157 Y101.759 E1.06737 ; perimeter
G1 X97.241 Y101.759 E1.12641 ; perimeter
G1 X97.241 Y98.241 E1.16865 ; perimeter
G1 X97.931 Y98.241 E1.17693 ; perimeter
G1 X97.999 Y98.241 E1.17775 ; perimeter
G1 F1560.000 E0.17775 ; retract
G92 E0 ; reset extrusion distance
G1 Z3.455 F18000.000 ; move to next layer (17)
G1 X98.051 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X100.786 Y100.128 F3000.000 E1.03991 ; perimeter
G1 X102.233 Y101.574 E1.06449 ; perimeter
G1 X102.157 Y101.759 E1.06688 ; perimeter
G1 X97.241 Y101.759 E1.12592 ; perimeter
G1 X97.241 Y98.241 E1.16817 ; perimeter
G1 X97.983 Y98.241 E1.17707 ; perimeter
G1 X98.051 Y98.241 E1.17789 ; perimeter
G1 F1560.000 E0.17789 ; retract
G92 E0 ; reset extrusion distance
G1 Z3.630 F18000.000 ; move to next layer (18)
G1 X98.104 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X100.670 Y100.011 F3000.000 E1.03745 ; perimeter
G1 X102.233 Y101.574 E1.06400 ; perimeter
G1 X102.157 Y101.759 E1.06639 ; perimeter
G1 X97.241 Y101.759 E1.12543 ; perimeter
G1 X97.241 Y98.241 E1.16768 ; perimeter
G1 X98.036 Y98.241 E1.17722 ; perimeter
G1 X98.104 Y98.241 E1.17804 ; perimeter
G1 F1560.000 E0.17804 ; retract
G92 E0 ; reset extrusion distance
G1 Z3.805 F18000.000 ; move to next layer (19)
G1 X98.156 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X100.553 Y99.895 F3000.000 E1.03498 ; perimeter
G1 X102.233 Y101.574 E1.06351 ; perimeter
G1 X102.157 Y101.759 E1.06591 ; perimeter
G1 X97.241 Y101.759 E1.12495 ; perimeter
G1 X97.241 Y98.241 E1.16719 ; perimeter
G1 X98.088 Y98.241 E1.17736 ; perimeter
G1 X98.156 Y98.241 E1.17818 ; perimeter
G1 F1560.000 E0.17818 ; retract
G92 E0 ; reset extrusion distance
G1 Z3.980 F18000.000 ; move to next layer (20)
G1 X98.209 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X100.436 Y99.778 F3000.000 E1.03251 ; perimeter
G1 X102.233 Y101.574 E1.06303 ; perimeter
G1 X102.157 Y101.759 E1.06542 ; perimeter
G1 X97.241 Y101.759 E1.12446 ; perimeter
G1 X97.241 Y98.241 E1.16671 ; perimeter
G1 X98.141 Y98.241 E1.17751 ; perimeter
G1 X98.209 Y98.241 E1.17832 ; perimeter
G1 F1560.000 E0.17832 ; retract
G92 E0 ; reset extrusion distance
G1 Z4.155 F18000.000 ; move to next layer (21)
G1 X98.261 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X100.320 Y99.661 F3000.000 E1.03004 ; perimeter
G1 X102.233 Y101.574 E1.06254 ; perimeter
G1 X102.157 Y101.759 E1.06493 ; perimeter
G1 X97.241 Y101.759 E1.12397 ; perimeter
G1 X97.241 Y98.241 E1.16622 ; perimeter
G1 X98.193 Y98.241 E1.17765 ; perimeter
G1 X98.261 Y98.241 E1.17847 ; perimeter
G1 F1560.000 E0.17847 ; retract
G92 E0 ; reset extrusion distance
G1 Z4.330 F18000.000 ; move to next layer (22)
G1 X98.314 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X100.203 Y99.545 F3000.000 E1.02757 ; perimeter
G1 X102.233 Y101.574 E1.06205 ; perimeter
G1 X102.157 Y101.759 E1.06445 ; perimeter
G1 X97.241 Y101.759 E1.12349 ; perimeter
G1 X97.241 Y98.241 E1.16573 ; perimeter
G1 X98.246 Y98.241 E1.17780 ; perimeter
G1 X98.314 Y98.241 E1.17861 ; perimeter
G1 F1560.000 E0.17861 ; retract
G92 E0 ; reset extrusion distance
G1 Z4.505 F18000.000 ; move to next layer (23)
G1 X98.366 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X100.086 Y99.428 F3000.000 E1.02510 ; perimeter
G1 X102.233 Y101.574 E1.06157 ; perimeter
G1 X102.157 Y101.759 E1.06396 ; perimeter
G1 X97.241 Y101.759 E1.12300 ; perimeter
G1 X97.241 Y98.241 E1.16525 ; perimeter
G1 X98.298 Y98.241 E1.17794 ; perimeter
G1 X98.366 Y98.241 E1.17876 ; perimeter
G1 F1560.000 E0.17876 ; retract
G92 E0 ; reset extrusion distance
G1 Z4.680 F18000.000 ; move to next layer (24)
G1 X98.419 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X99.970 Y99.311 F3000.000 E1.02264 ; perimeter
G1 X102.233 Y101.574 E1.06108 ; perimeter
G1 X102.157 Y101.759 E1.06347 ; perimeter
G1 X97.241 Y101.759 E1.12252 ; perimeter
G1 X97.241 Y98.241 E1.16476 ; perimeter
G1 X98.351 Y98.241 E1.17808 ; perimeter
G1 X98.419 Y98.241 E1.17890 ; perimeter
G1 F1560.000 E0.17890 ; retract
G92 E0 ; reset extrusion distance
G1 Z4.855 F18000.000 ; move to next layer (25)
G1 X98.471 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X99.853 Y99.195 F3000.000 E1.02017 ; perimeter
G1 X102.233 Y101.574 E1.06059 ; perimeter
G1 X102.157 Y101.759 E1.06299 ; perimeter
G1 X97.241 Y101.759 E1.12203 ; perimeter
G1 X97.241 Y98.241 E1.16428 ; perimeter
G1 X98.403 Y98.241 E1.17823 ; perimeter
G1 X98.471 Y98.241 E1.17904 ; perimeter
G1 F1560.000 E0.17904 ; retract
G92 E0 ; reset extrusion distance
G1 Z5.030 F18000.000 ; move to next layer (26)
G1 X98.524 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X99.736 Y99.078 F3000.000 E1.01770 ; perimeter
G1 X102.233 Y101.574 E1.06011 ; perimeter
G1 X102.157 Y101.759 E1.06250 ; perimeter
G1 X97.241 Y101.759 E1.12154 ; perimeter
G1 X97.241 Y98.241 E1.16379 ; perimeter
G1 X98.456 Y98.241 E1.17837 ; perimeter
G1 X98.524 Y98.241 E1.17919 ; perimeter
G1 F1560.000 E0.17919 ; retract
G92 E0 ; reset extrusion distance
G1 Z5.205 F18000.000 ; move to next layer (27)
G1 X98.576 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X99.620 Y98.961 F3000.000 E1.01523 ; perimeter
G1 X102.233 Y101.574 E1.05962 ; perimeter
G1 X102.157 Y101.759 E1.06201 ; perimeter
G1 X97.241 Y101.759 E1.12106 ; perimeter
G1 X97.241 Y98.241 E1.16330 ; perimeter
G1 X98.508 Y98.241 E1.17852 ; perimeter
G1 X98.576 Y98.241 E1.17933 ; perimeter
G1 F1560.000 E0.17933 ; retract
G92 E0 ; reset extrusion distance
G1 Z5.380 F18000.000 ; move to next layer (28)
G1 X98.629 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X99.503 Y98.845 F3000.000 E1.01276 ; perimeter
G1 X102.233 Y101.574 E1.05913 ; perimeter
G1 X102.157 Y101.759 E1.06153 ; perimeter
G1 X97.241 Y101.759 E1.12057 ; perimeter
G1 X97.241 Y98.241 E1.16282 ; perimeter
G1 X98.561 Y98.241 E1.17866 ; perimeter
G1 X98.629 Y98.241 E1.17948 ; perimeter
G1 F1560.000 E0.17948 ; retract
G92 E0 ; reset extrusion distance
G1 Z5.555 F18000.000 ; move to next layer (29)
G1 X98.681 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X99.386 Y98.728 F3000.000 E1.01029 ; perimeter
G1 X102.233 Y101.574 E1.05865 ; perimeter
G1 X102.157 Y101.759 E1.06104 ; perimeter
G1 X97.241 Y101.759 E1.12008 ; perimeter
G1 X97.241 Y98.241 E1.16233 ; perimeter
G1 X98.613 Y98.241 E1.17880 ; perimeter
G1 X98.681 Y98.241 E1.17962 ; perimeter
G1 F1560.000 E0.17962 ; retract
G92 E0 ; reset extrusion distance
G1 Z5.730 F18000.000 ; move to next layer (30)
G1 X98.734 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X99.270 Y98.611 F3000.000 E1.00782 ; perimeter
G1 X102.233 Y101.574 E1.05816 ; perimeter
G1 X102.157 Y101.759 E1.06055 ; perimeter
G1 X97.241 Y101.759 E1.11960 ; perimeter
G1 X97.241 Y98.241 E1.16184 ; perimeter
G1 X98.666 Y98.241 E1.17895 ; perimeter
G1 X98.734 Y98.241 E1.17977 ; perimeter
G1 F1560.000 E0.17977 ; retract
G92 E0 ; reset extrusion distance
G1 Z5.905 F18000.000 ; move to next layer (31)
G1 X98.786 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X99.153 Y98.495 F3000.000 E1.00536 ; perimeter
G1 X102.233 Y101.574 E1.05767 ; perimeter
G1 X102.157 Y101.759 E1.06007 ; perimeter
G1 X97.241 Y101.759 E1.11911 ; perimeter
G1 X97.241 Y98.241 E1.16136 ; perimeter
G1 X98.718 Y98.241 E1.17909 ; perimeter
G1 X98.786 Y98.241 E1.17991 ; perimeter
G1 F1560.000 E0.17991 ; retract
G92 E0 ; reset extrusion distance
G1 Z6.080 F18000.000 ; move to next layer (32)
G1 X98.839 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X99.036 Y98.378 F3000.000 E1.00289 ; perimeter
G1 X102.233 Y101.574 E1.05719 ; perimeter
G1 X102.157 Y101.759 E1.05958 ; perimeter
G1 X97.241 Y101.759 E1.11862 ; perimeter
G1 X97.241 Y98.241 E1.16087 ; perimeter
G1 X98.771 Y98.241 E1.17924 ; perimeter
G1 X98.839 Y98.241 E1.18005 ; perimeter
G1 F1560.000 E0.18005 ; retract
G92 E0 ; reset extrusion distance
G1 Z6.255 F18000.000 ; move to next layer (33)
G1 X98.900 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X102.233 Y101.574 F3000.000 E1.05662 ; perimeter
G1 X102.157 Y101.759 E1.05901 ; perimeter
G1 X97.241 Y101.759 E1.11805 ; perimeter
G1 X97.241 Y98.241 E1.16030 ; perimeter
G1 X98.832 Y98.241 E1.17940 ; perimeter
G1 X98.900 Y98.241 E1.18022 ; perimeter
G1 F1560.000 E0.18022 ; retract
G92 E0 ; reset extrusion distance
M107 ; disable fan
M104 S135 ; turn down - not off- temperature
G28 Y0  ; home X axis
M106
M84     ; disable motors
; filament used = 6.1mm (0.0cm3)
