; generated by Slic3r 0.9.6-dev on 2012-11-19 at 11:50:47

; layer_height = .175
; perimeters = 1
; top_solid_layers = 0
; bottom_solid_layers = 0
; fill_density = 0
; perimeter_speed = 130
; infill_speed = 130
; travel_speed = 300
; scale = 1
; nozzle_diameter = .345
; filament_diameter = 2.9
; extrusion_multiplier = 1
; perimeters extrusion width = 0.48mm
; infill extrusion width = 0.48mm
; first layer extrusion width = 0.48mm

G90 ; use absolute coordinates
G21 ; set units to millimeters
M82 ; use absolute distances for extrusion
G28 ; go home and zero the axes
G92 X0 Y0 Z0 E0.0
G1 Z1.0 F240 ; Head on up to a location I can be seen.
G1 E5 ; let's spew a little.
G92 E2.0
G1 E0.0 ; retract a little so I stop drooling.
G1 X0 Y0 Z0 F3000
G1 Y30
G1 X30 
G1 Y0 
G1 X100 Y0 Z1.0
G1 X100 Y30 Z0 E3
G92 E0
M106
G90 ; use absolute coordinates
G21 ; set units to millimeters
G92 E0 ; reset extrusion distance
M82 ; use absolute distances for extrusion
M106 S255 ; enable fan
G1 F1560.000 E-1.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z0.480 F18000.000 ; move to next layer (0)
G1 X97.241 Y98.469 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X97.380 Y98.397 F3000.000 E1.00214 ; perimeter
G1 X101.909 Y101.520 E1.07767 ; perimeter
G1 X101.834 Y101.759 E1.08110 ; perimeter
G1 X97.241 Y101.759 E1.14415 ; perimeter
G1 X97.241 Y98.537 E1.18837 ; perimeter
G1 X97.241 Y98.469 E1.18930 ; perimeter
G1 F1560.000 E0.18930 ; retract
G92 E0 ; reset extrusion distance
G1 X102.506 Y101.849 F18000.000 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X102.704 Y101.923 F3000.000 E1.00290 ; perimeter
G1 X102.311 Y101.780 F9036.702 ; move to first perimeter point
G1 X102.506 Y101.849 F3000.000 E1.00574 ; perimeter
G1 X102.305 Y101.774 F1127.960 ; move to first perimeter point
G1 X102.308 Y101.784 F3000.000 E1.00588 ; perimeter
G1 X100.819 Y101.495 F433.373 ; move to first fill point
G1 X100.651 Y101.327 F3000.000 E1.00793 ; fill
G1 X101.223 Y101.495 F1014.914 ; move to first fill point
G1 X101.054 Y101.327 F3000.000 E1.00999 ; fill
G1 F1560.000 E0.00999 ; retract
G92 E0 ; reset extrusion distance
G1 X97.673 Y99.070 F3967.999 ; move to first fill point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X97.505 Y98.902 F3000.000 E1.00190 ; fill
G1 F1560.000 E0.00190 ; retract
G92 E0 ; reset extrusion distance
G1 Z0.655 F18000.000 ; move to next layer (1)
G1 X97.241 Y98.430 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X97.380 Y98.358 F3000.000 E1.00188 ; perimeter
G1 X101.965 Y101.520 E1.06878 ; perimeter
G1 X101.891 Y101.759 E1.07178 ; perimeter
G1 X97.241 Y101.759 E1.12763 ; perimeter
G1 X97.241 Y98.499 E1.16679 ; perimeter
G1 X97.241 Y98.430 E1.16760 ; perimeter
G1 F1560.000 E0.16760 ; retract
G92 E0 ; reset extrusion distance
G1 X102.638 Y101.856 F18000.000 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X102.651 Y101.875 F3000.000 E1.00027 ; perimeter
G1 X102.361 Y101.773 F8201.354 ; move to first perimeter point
G1 X102.638 Y101.856 F3000.000 E1.00374 ; perimeter
G1 X102.360 Y101.774 F1596.063 ; move to first perimeter point
G1 X102.361 Y101.773 F3000.000 E1.00376 ; perimeter
G1 X101.279 Y101.327 F669.248 ; move to first fill point
G1 X101.111 Y101.495 F3000.000 E1.00626 ; fill
G1 X100.947 Y101.098 F801.014 ; move to first fill point
G1 X100.779 Y101.266 F3000.000 E1.00876 ; fill
G1 F1560.000 E0.00876 ; retract
G92 E0 ; reset extrusion distance
G1 X97.692 Y98.853 F3619.255 ; move to first fill point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X97.523 Y99.021 F3000.000 E1.00166 ; fill
G1 F1560.000 E0.00166 ; retract
G92 E0 ; reset extrusion distance
G1 Z0.830 F18000.000 ; move to next layer (2)
G1 X97.241 Y98.394 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X97.380 Y98.322 F3000.000 E1.00188 ; perimeter
G1 X102.017 Y101.520 E1.06955 ; perimeter
G1 X101.943 Y101.759 E1.07255 ; perimeter
G1 X97.241 Y101.759 E1.12902 ; perimeter
G1 X97.241 Y98.462 E1.16862 ; perimeter
G1 X97.241 Y98.394 E1.16943 ; perimeter
G1 F1560.000 E0.16943 ; retract
G92 E0 ; reset extrusion distance
G1 X102.670 Y101.865 F18000.000 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X102.674 Y101.864 F3000.000 E1.00004 ; perimeter
G1 X102.414 Y101.777 F8163.441 ; move to first perimeter point
G1 X102.670 Y101.865 F3000.000 E1.00330 ; perimeter
G1 X102.411 Y101.773 F1480.408 ; move to first perimeter point
G1 X102.414 Y101.777 F3000.000 E1.00335 ; perimeter
G1 X100.928 Y101.495 F422.576 ; move to first fill point
G1 X100.760 Y101.327 F3000.000 E1.00515 ; fill
G1 X101.331 Y101.495 F1004.117 ; move to first fill point
G1 X101.163 Y101.327 F3000.000 E1.00695 ; fill
G1 F1560.000 E0.00695 ; retract
G92 E0 ; reset extrusion distance
G1 X97.673 Y98.995 F4080.525 ; move to first fill point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X97.505 Y98.827 F3000.000 E1.00166 ; fill
G1 F1560.000 E0.00166 ; retract
G92 E0 ; reset extrusion distance
G1 Z1.005 F18000.000 ; move to next layer (3)
G1 X97.241 Y98.358 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X97.380 Y98.285 F3000.000 E1.00188 ; perimeter
G1 X102.070 Y101.520 E1.07031 ; perimeter
G1 X101.996 Y101.759 E1.07331 ; perimeter
G1 X97.241 Y101.759 E1.13042 ; perimeter
G1 X97.241 Y98.426 E1.17045 ; perimeter
G1 X97.241 Y98.358 E1.17127 ; perimeter
G1 F1560.000 E0.17127 ; retract
G92 E0 ; reset extrusion distance
G1 X102.502 Y101.790 F18000.000 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X102.702 Y101.873 F3000.000 E1.00261 ; perimeter
G1 X102.459 Y101.772 F9047.149 ; move to first perimeter point
G1 X102.502 Y101.790 F3000.000 E1.00316 ; perimeter
G1 X102.442 Y101.649 F247.119 ; move to first perimeter point
G1 X102.459 Y101.772 F3000.000 E1.00465 ; perimeter
G1 X101.384 Y101.327 F707.175 ; move to first fill point
G1 X101.216 Y101.495 F3000.000 E1.00715 ; fill
G1 X101.052 Y101.098 F667.333 ; move to first fill point
G1 X100.884 Y101.266 F3000.000 E1.00965 ; fill
G1 F1560.000 E0.00965 ; retract
G92 E0 ; reset extrusion distance
G1 X97.692 Y98.781 F3727.889 ; move to first fill point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X97.523 Y98.949 F3000.000 E1.00166 ; fill
G1 F1560.000 E0.00166 ; retract
G92 E0 ; reset extrusion distance
G1 Z1.180 F18000.000 ; move to next layer (4)
G1 X97.241 Y98.322 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X97.380 Y98.249 F3000.000 E1.00188 ; perimeter
G1 X102.122 Y101.520 E1.07108 ; perimeter
G1 X102.048 Y101.759 E1.07408 ; perimeter
G1 X97.241 Y101.759 E1.13182 ; perimeter
G1 X97.241 Y98.390 E1.17228 ; perimeter
G1 X97.241 Y98.322 E1.17310 ; perimeter
G1 F1560.000 E0.17310 ; retract
G92 E0 ; reset extrusion distance
G1 X102.696 Y101.867 F18000.000 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X102.710 Y101.891 F3000.000 E1.00033 ; perimeter
G1 X102.498 Y101.773 F8315.983 ; move to first perimeter point
G1 X102.696 Y101.867 F3000.000 E1.00296 ; perimeter
G1 X102.490 Y101.765 F1141.512 ; move to first perimeter point
G1 X102.498 Y101.773 F3000.000 E1.00309 ; perimeter
G1 X101.033 Y101.495 F417.608 ; move to first fill point
G1 X100.865 Y101.327 F3000.000 E1.00489 ; fill
G1 X101.436 Y101.495 F999.174 ; move to first fill point
G1 X101.268 Y101.327 F3000.000 E1.00668 ; fill
G1 F1560.000 E0.00668 ; retract
G92 E0 ; reset extrusion distance
G1 Z1.355 F18000.000 ; move to next layer (5)
G1 X97.241 Y98.286 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X97.380 Y98.213 F3000.000 E1.00188 ; perimeter
G1 X102.175 Y101.520 E1.07185 ; perimeter
G1 X102.101 Y101.759 E1.07485 ; perimeter
G1 X97.241 Y101.759 E1.13321 ; perimeter
G1 X97.241 Y98.354 E1.17411 ; perimeter
G1 X97.241 Y98.286 E1.17493 ; perimeter
G1 F1560.000 E0.17493 ; retract
G92 E0 ; reset extrusion distance
G1 X101.489 Y101.327 F18000.000 ; move to first fill point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X101.321 Y101.495 F3000.000 E1.00250 ; fill
G1 X101.157 Y101.098 F6371.013 ; move to first fill point
G1 X100.989 Y101.266 F3000.000 E1.00500 ; fill
G1 F1560.000 E0.00500 ; retract
G92 E0 ; reset extrusion distance
G1 X97.692 Y98.708 F3836.510 ; move to first fill point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X97.523 Y98.876 F3000.000 E1.00166 ; fill
G1 F1560.000 E0.00166 ; retract
G92 E0 ; reset extrusion distance
G1 Z1.530 F18000.000 ; move to next layer (6)
G1 X97.241 Y98.249 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X97.380 Y98.177 F3000.000 E1.00188 ; perimeter
G1 X102.227 Y101.520 E1.07261 ; perimeter
G1 X102.153 Y101.759 E1.07561 ; perimeter
G1 X97.241 Y101.759 E1.13461 ; perimeter
G1 X97.241 Y98.317 E1.17594 ; perimeter
G1 X97.241 Y98.249 E1.17676 ; perimeter
G1 F1560.000 E0.17676 ; retract
G92 E0 ; reset extrusion distance
G1 X101.138 Y101.495 F18000.000 ; move to first fill point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X100.970 Y101.327 F3000.000 E1.00180 ; fill
G1 X101.541 Y101.495 F5844.445 ; move to first fill point
G1 X101.373 Y101.327 F3000.000 E1.00360 ; fill
G1 F1560.000 E0.00360 ; retract
G92 E0 ; reset extrusion distance
G1 X97.673 Y98.850 F4297.757 ; move to first fill point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X97.505 Y98.682 F3000.000 E1.00166 ; fill
G1 F1560.000 E0.00166 ; retract
G92 E0 ; reset extrusion distance
G1 Z1.705 F18000.000 ; move to next layer (7)
G1 X97.241 Y98.213 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X97.380 Y98.141 F3000.000 E1.00188 ; perimeter
G1 X101.953 Y101.295 E1.06861 ; perimeter
G1 X102.233 Y101.574 E1.07336 ; perimeter
G1 X102.157 Y101.759 E1.07576 ; perimeter
G1 X97.241 Y101.759 E1.13480 ; perimeter
G1 X97.241 Y98.281 E1.17657 ; perimeter
G1 X97.241 Y98.213 E1.17738 ; perimeter
G1 F1560.000 E0.17738 ; retract
G92 E0 ; reset extrusion distance
G1 X101.594 Y101.327 F18000.000 ; move to first fill point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X101.426 Y101.495 F3000.000 E1.00250 ; fill
G1 X101.262 Y101.098 F6528.511 ; move to first fill point
G1 X101.094 Y101.266 F3000.000 E1.00500 ; fill
G1 F1560.000 E0.00500 ; retract
G92 E0 ; reset extrusion distance
G1 Z1.880 F18000.000 ; move to next layer (8)
G1 X97.241 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X97.579 Y98.241 F3000.000 E1.00405 ; perimeter
G1 X101.836 Y101.178 E1.06618 ; perimeter
G1 X102.233 Y101.574 E1.07291 ; perimeter
G1 X102.157 Y101.759 E1.07531 ; perimeter
G1 X97.241 Y101.759 E1.13435 ; perimeter
G1 X97.241 Y98.310 E1.17578 ; perimeter
G1 X97.241 Y98.241 E1.17659 ; perimeter
G1 F1560.000 E0.17659 ; retract
G92 E0 ; reset extrusion distance
G1 X101.243 Y101.495 F18000.000 ; move to first fill point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X101.075 Y101.327 F3000.000 E1.00180 ; fill
G1 X101.646 Y101.495 F6001.950 ; move to first fill point
G1 X101.478 Y101.327 F3000.000 E1.00360 ; fill
G1 F1560.000 E0.00360 ; retract
G92 E0 ; reset extrusion distance
G1 X97.673 Y98.777 F4406.390 ; move to first fill point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X97.505 Y98.609 F3000.000 E1.00166 ; fill
G1 F1560.000 E0.00166 ; retract
G92 E0 ; reset extrusion distance
G1 Z2.055 F18000.000 ; move to next layer (9)
G1 X97.241 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X97.631 Y98.241 F3000.000 E1.00468 ; perimeter
G1 X101.720 Y101.061 E1.06434 ; perimeter
G1 X102.233 Y101.574 E1.07306 ; perimeter
G1 X102.157 Y101.759 E1.07545 ; perimeter
G1 X97.241 Y101.759 E1.13449 ; perimeter
G1 X97.241 Y98.310 E1.17592 ; perimeter
G1 X97.241 Y98.241 E1.17674 ; perimeter
G1 F1560.000 E0.17674 ; retract
G92 E0 ; reset extrusion distance
G1 X101.662 Y101.327 F18000.000 ; move to first fill point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X101.494 Y101.495 F3000.000 E1.00233 ; fill
G1 X101.367 Y101.098 F6630.867 ; move to first fill point
G1 X101.199 Y101.266 F3000.000 E1.00467 ; fill
G1 F1560.000 E0.00467 ; retract
G92 E0 ; reset extrusion distance
G1 X97.692 Y98.563 F4053.750 ; move to first fill point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X97.523 Y98.732 F3000.000 E1.00166 ; fill
G1 F1560.000 E0.00166 ; retract
G92 E0 ; reset extrusion distance
G1 Z2.230 F18000.000 ; move to next layer (10)
G1 X97.241 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X97.684 Y98.241 F3000.000 E1.00531 ; perimeter
G1 X101.603 Y100.945 E1.06250 ; perimeter
G1 X102.233 Y101.574 E1.07320 ; perimeter
G1 X102.157 Y101.759 E1.07560 ; perimeter
G1 X97.241 Y101.759 E1.13464 ; perimeter
G1 X97.241 Y98.310 E1.17607 ; perimeter
G1 X97.241 Y98.241 E1.17688 ; perimeter
G1 F1560.000 E0.17688 ; retract
G92 E0 ; reset extrusion distance
G1 Z2.405 F18000.000 ; move to next layer (11)
G1 X97.241 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X97.736 Y98.241 F3000.000 E1.00594 ; perimeter
G1 X101.486 Y100.828 E1.06067 ; perimeter
G1 X102.233 Y101.574 E1.07335 ; perimeter
G1 X102.157 Y101.759 E1.07574 ; perimeter
G1 X97.241 Y101.759 E1.13478 ; perimeter
G1 X97.241 Y98.310 E1.17621 ; perimeter
G1 X97.241 Y98.241 E1.17703 ; perimeter
G1 F1560.000 E0.17703 ; retract
G92 E0 ; reset extrusion distance
G1 Z2.580 F18000.000 ; move to next layer (12)
G1 X97.241 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X97.789 Y98.241 F3000.000 E1.00657 ; perimeter
G1 X101.370 Y100.711 E1.05883 ; perimeter
G1 X102.233 Y101.574 E1.07349 ; perimeter
G1 X102.157 Y101.759 E1.07588 ; perimeter
G1 X97.241 Y101.759 E1.13492 ; perimeter
G1 X97.241 Y98.310 E1.17635 ; perimeter
G1 X97.241 Y98.241 E1.17717 ; perimeter
G1 F1560.000 E0.17717 ; retract
G92 E0 ; reset extrusion distance
G1 Z2.755 F18000.000 ; move to next layer (13)
G1 X97.241 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X97.841 Y98.241 F3000.000 E1.00720 ; perimeter
G1 X101.253 Y100.595 E1.05699 ; perimeter
G1 X102.233 Y101.574 E1.07363 ; perimeter
G1 X102.157 Y101.759 E1.07603 ; perimeter
G1 X97.241 Y101.759 E1.13507 ; perimeter
G1 X97.241 Y98.310 E1.17650 ; perimeter
G1 X97.241 Y98.241 E1.17732 ; perimeter
G1 F1560.000 E0.17732 ; retract
G92 E0 ; reset extrusion distance
G1 Z2.930 F18000.000 ; move to next layer (14)
G1 X97.241 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X97.894 Y98.241 F3000.000 E1.00783 ; perimeter
G1 X101.136 Y100.478 E1.05515 ; perimeter
G1 X102.233 Y101.574 E1.07378 ; perimeter
G1 X102.157 Y101.759 E1.07617 ; perimeter
G1 X97.241 Y101.759 E1.13521 ; perimeter
G1 X97.241 Y98.310 E1.17664 ; perimeter
G1 X97.241 Y98.241 E1.17746 ; perimeter
G1 F1560.000 E0.17746 ; retract
G92 E0 ; reset extrusion distance
G1 Z3.105 F18000.000 ; move to next layer (15)
G1 X97.241 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X97.946 Y98.241 F3000.000 E1.00846 ; perimeter
G1 X101.020 Y100.361 E1.05331 ; perimeter
G1 X102.233 Y101.574 E1.07392 ; perimeter
G1 X102.157 Y101.759 E1.07632 ; perimeter
G1 X97.241 Y101.759 E1.13536 ; perimeter
G1 X97.241 Y98.310 E1.17679 ; perimeter
G1 X97.241 Y98.241 E1.17760 ; perimeter
G1 F1560.000 E0.17760 ; retract
G92 E0 ; reset extrusion distance
G1 Z3.280 F18000.000 ; move to next layer (16)
G1 X97.241 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X97.999 Y98.241 F3000.000 E1.00909 ; perimeter
G1 X100.903 Y100.245 E1.05148 ; perimeter
G1 X102.233 Y101.574 E1.07407 ; perimeter
G1 X102.157 Y101.759 E1.07646 ; perimeter
G1 X97.241 Y101.759 E1.13550 ; perimeter
G1 X97.241 Y98.310 E1.17693 ; perimeter
G1 X97.241 Y98.241 E1.17775 ; perimeter
G1 F1560.000 E0.17775 ; retract
G92 E0 ; reset extrusion distance
G1 Z3.455 F18000.000 ; move to next layer (17)
G1 X97.241 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X98.051 Y98.241 F3000.000 E1.00972 ; perimeter
G1 X100.786 Y100.128 E1.04964 ; perimeter
G1 X102.233 Y101.574 E1.07421 ; perimeter
G1 X102.157 Y101.759 E1.07660 ; perimeter
G1 X97.241 Y101.759 E1.13565 ; perimeter
G1 X97.241 Y98.310 E1.17707 ; perimeter
G1 X97.241 Y98.241 E1.17789 ; perimeter
G1 F1560.000 E0.17789 ; retract
G92 E0 ; reset extrusion distance
G1 Z3.630 F18000.000 ; move to next layer (18)
G1 X97.241 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X98.104 Y98.241 F3000.000 E1.01036 ; perimeter
G1 X100.670 Y100.011 E1.04780 ; perimeter
G1 X102.233 Y101.574 E1.07435 ; perimeter
G1 X102.157 Y101.759 E1.07675 ; perimeter
G1 X97.241 Y101.759 E1.13579 ; perimeter
G1 X97.241 Y98.310 E1.17722 ; perimeter
G1 X97.241 Y98.241 E1.17804 ; perimeter
G1 F1560.000 E0.17804 ; retract
G92 E0 ; reset extrusion distance
G1 Z3.805 F18000.000 ; move to next layer (19)
G1 X97.241 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X98.156 Y98.241 F3000.000 E1.01099 ; perimeter
G1 X100.553 Y99.895 E1.04596 ; perimeter
G1 X102.233 Y101.574 E1.07450 ; perimeter
G1 X102.157 Y101.759 E1.07689 ; perimeter
G1 X97.241 Y101.759 E1.13593 ; perimeter
G1 X97.241 Y98.310 E1.17736 ; perimeter
G1 X97.241 Y98.241 E1.17818 ; perimeter
G1 F1560.000 E0.17818 ; retract
G92 E0 ; reset extrusion distance
G1 Z3.980 F18000.000 ; move to next layer (20)
G1 X97.241 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X98.209 Y98.241 F3000.000 E1.01162 ; perimeter
G1 X100.436 Y99.778 E1.04413 ; perimeter
G1 X102.233 Y101.574 E1.07464 ; perimeter
G1 X102.157 Y101.759 E1.07704 ; perimeter
G1 X97.241 Y101.759 E1.13608 ; perimeter
G1 X97.241 Y98.310 E1.17751 ; perimeter
G1 X97.241 Y98.241 E1.17832 ; perimeter
G1 F1560.000 E0.17832 ; retract
G92 E0 ; reset extrusion distance
G1 Z4.155 F18000.000 ; move to next layer (21)
G1 X97.241 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X98.261 Y98.241 F3000.000 E1.01225 ; perimeter
G1 X100.320 Y99.661 E1.04229 ; perimeter
G1 X102.233 Y101.574 E1.07479 ; perimeter
G1 X102.157 Y101.759 E1.07718 ; perimeter
G1 X97.241 Y101.759 E1.13622 ; perimeter
G1 X97.241 Y98.310 E1.17765 ; perimeter
G1 X97.241 Y98.241 E1.17847 ; perimeter
G1 F1560.000 E0.17847 ; retract
G92 E0 ; reset extrusion distance
G1 Z4.330 F18000.000 ; move to next layer (22)
G1 X97.241 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X98.314 Y98.241 F3000.000 E1.01288 ; perimeter
G1 X100.203 Y99.545 E1.04045 ; perimeter
G1 X102.233 Y101.574 E1.07493 ; perimeter
G1 X102.157 Y101.759 E1.07732 ; perimeter
G1 X97.241 Y101.759 E1.13637 ; perimeter
G1 X97.241 Y98.310 E1.17780 ; perimeter
G1 X97.241 Y98.241 E1.17861 ; perimeter
G1 F1560.000 E0.17861 ; retract
G92 E0 ; reset extrusion distance
G1 Z4.505 F18000.000 ; move to next layer (23)
G1 X97.241 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X98.366 Y98.241 F3000.000 E1.01351 ; perimeter
G1 X100.086 Y99.428 E1.03861 ; perimeter
G1 X102.233 Y101.574 E1.07508 ; perimeter
G1 X102.157 Y101.759 E1.07747 ; perimeter
G1 X97.241 Y101.759 E1.13651 ; perimeter
G1 X97.241 Y98.310 E1.17794 ; perimeter
G1 X97.241 Y98.241 E1.17876 ; perimeter
G1 F1560.000 E0.17876 ; retract
G92 E0 ; reset extrusion distance
G1 Z4.680 F18000.000 ; move to next layer (24)
G1 X97.241 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X98.419 Y98.241 F3000.000 E1.01414 ; perimeter
G1 X99.970 Y99.311 E1.03677 ; perimeter
G1 X102.233 Y101.574 E1.07522 ; perimeter
G1 X102.157 Y101.759 E1.07761 ; perimeter
G1 X97.241 Y101.759 E1.13665 ; perimeter
G1 X97.241 Y98.310 E1.17808 ; perimeter
G1 X97.241 Y98.241 E1.17890 ; perimeter
G1 F1560.000 E0.17890 ; retract
G92 E0 ; reset extrusion distance
G1 Z4.855 F18000.000 ; move to next layer (25)
G1 X97.241 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X98.471 Y98.241 F3000.000 E1.01477 ; perimeter
G1 X99.853 Y99.195 E1.03494 ; perimeter
G1 X102.233 Y101.574 E1.07536 ; perimeter
G1 X102.157 Y101.759 E1.07776 ; perimeter
G1 X97.241 Y101.759 E1.13680 ; perimeter
G1 X97.241 Y98.310 E1.17823 ; perimeter
G1 X97.241 Y98.241 E1.17904 ; perimeter
G1 F1560.000 E0.17904 ; retract
G92 E0 ; reset extrusion distance
G1 Z5.030 F18000.000 ; move to next layer (26)
G1 X97.241 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X98.524 Y98.241 F3000.000 E1.01540 ; perimeter
G1 X99.736 Y99.078 E1.03310 ; perimeter
G1 X102.233 Y101.574 E1.07551 ; perimeter
G1 X102.157 Y101.759 E1.07790 ; perimeter
G1 X97.241 Y101.759 E1.13694 ; perimeter
G1 X97.241 Y98.310 E1.17837 ; perimeter
G1 X97.241 Y98.241 E1.17919 ; perimeter
G1 F1560.000 E0.17919 ; retract
G92 E0 ; reset extrusion distance
G1 Z5.205 F18000.000 ; move to next layer (27)
G1 X97.241 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X98.576 Y98.241 F3000.000 E1.01603 ; perimeter
G1 X99.620 Y98.961 E1.03126 ; perimeter
G1 X102.233 Y101.574 E1.07565 ; perimeter
G1 X102.157 Y101.759 E1.07804 ; perimeter
G1 X97.241 Y101.759 E1.13709 ; perimeter
G1 X97.241 Y98.310 E1.17852 ; perimeter
G1 X97.241 Y98.241 E1.17933 ; perimeter
G1 F1560.000 E0.17933 ; retract
G92 E0 ; reset extrusion distance
G1 Z5.380 F18000.000 ; move to next layer (28)
G1 X97.241 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X98.629 Y98.241 F3000.000 E1.01666 ; perimeter
G1 X99.503 Y98.845 E1.02942 ; perimeter
G1 X102.233 Y101.574 E1.07580 ; perimeter
G1 X102.157 Y101.759 E1.07819 ; perimeter
G1 X97.241 Y101.759 E1.13723 ; perimeter
G1 X97.241 Y98.310 E1.17866 ; perimeter
G1 X97.241 Y98.241 E1.17948 ; perimeter
G1 F1560.000 E0.17948 ; retract
G92 E0 ; reset extrusion distance
G1 Z5.555 F18000.000 ; move to next layer (29)
G1 X97.241 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X98.681 Y98.241 F3000.000 E1.01729 ; perimeter
G1 X99.386 Y98.728 E1.02759 ; perimeter
G1 X102.233 Y101.574 E1.07594 ; perimeter
G1 X102.157 Y101.759 E1.07833 ; perimeter
G1 X97.241 Y101.759 E1.13737 ; perimeter
G1 X97.241 Y98.310 E1.17880 ; perimeter
G1 X97.241 Y98.241 E1.17962 ; perimeter
G1 F1560.000 E0.17962 ; retract
G92 E0 ; reset extrusion distance
G1 Z5.730 F18000.000 ; move to next layer (30)
G1 X97.241 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X98.734 Y98.241 F3000.000 E1.01792 ; perimeter
G1 X99.270 Y98.611 E1.02575 ; perimeter
G1 X102.233 Y101.574 E1.07608 ; perimeter
G1 X102.157 Y101.759 E1.07848 ; perimeter
G1 X97.241 Y101.759 E1.13752 ; perimeter
G1 X97.241 Y98.310 E1.17895 ; perimeter
G1 X97.241 Y98.241 E1.17977 ; perimeter
G1 F1560.000 E0.17977 ; retract
G92 E0 ; reset extrusion distance
G1 Z5.905 F18000.000 ; move to next layer (31)
G1 X97.241 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X98.786 Y98.241 F3000.000 E1.01855 ; perimeter
G1 X99.153 Y98.495 E1.02391 ; perimeter
G1 X102.233 Y101.574 E1.07623 ; perimeter
G1 X102.157 Y101.759 E1.07862 ; perimeter
G1 X97.241 Y101.759 E1.13766 ; perimeter
G1 X97.241 Y98.310 E1.17909 ; perimeter
G1 X97.241 Y98.241 E1.17991 ; perimeter
G1 F1560.000 E0.17991 ; retract
G92 E0 ; reset extrusion distance
G1 Z6.080 F18000.000 ; move to next layer (32)
G1 X97.241 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X98.839 Y98.241 F3000.000 E1.01918 ; perimeter
G1 X99.036 Y98.378 E1.02207 ; perimeter
G1 X102.233 Y101.574 E1.07637 ; perimeter
G1 X102.157 Y101.759 E1.07877 ; perimeter
G1 X97.241 Y101.759 E1.13781 ; perimeter
G1 X97.241 Y98.310 E1.17924 ; perimeter
G1 X97.241 Y98.241 E1.18005 ; perimeter
G1 F1560.000 E0.18005 ; retract
G92 E0 ; reset extrusion distance
G1 Z6.255 F18000.000 ; move to next layer (33)
G1 X97.241 Y98.241 ; move to first perimeter point
G1 F1560.000 E1.00000 ; compensate retraction
G1 X98.900 Y98.241 F3000.000 E1.01992 ; perimeter
G1 X102.233 Y101.574 E1.07654 ; perimeter
G1 X102.157 Y101.759 E1.07893 ; perimeter
G1 X97.241 Y101.759 E1.13798 ; perimeter
G1 X97.241 Y98.310 E1.17940 ; perimeter
G1 X97.241 Y98.241 E1.18022 ; perimeter
G1 F1560.000 E0.18022 ; retract
G92 E0 ; reset extrusion distance
M107 ; disable fan
M104 S135 ; turn down - not off- temperature
G28 Y0  ; home X axis
M106
M84     ; disable motors
; filament used = 6.1mm (0.0cm3)

; acceleration = 0
; bed_size = 200,200
; bed_temperature = 0
; bottom_solid_layers = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 1.16
; bridge_speed = 5
; brim_width = 0
; complete_objects = 
; cooling = 1
; disable_fan_first_layers = 0
; duplicate = 1
; duplicate_distance = 6
; duplicate_grid = 1,1
; end_gcode = M104 S135 ; turn down - not off- temperature\nG28 Y0  ; home X axis\nM106\nM84     ; disable motors
; external_perimeter_speed = 60%
; extra_perimeters = 
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0
; fan_always_on = 1
; fan_below_layer_time = 1000
; filament_diameter = 2.9
; fill_angle = 45
; fill_density = 0
; fill_pattern = rectilinear
; first_layer_bed_temperature = 0
; first_layer_extrusion_width = 0
; first_layer_height = .2
; first_layer_speed = 50%
; first_layer_temperature = 0
; g0 = 0
; gcode_arcs = 0
; gcode_comments = 1
; gcode_flavor = reprap
; infill_acceleration = 50
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0
; infill_speed = 130
; layer_gcode = 
; layer_height = .175
; max_fan_speed = 100
; min_fan_speed = 100
; min_print_speed = 50
; min_skirt_length = 0
; notes = This config has a workaround for the extrusion retraction compensation bug for the first layer... be sure to comment out those 3 lines IF the bug has been fixed.
; nozzle_diameter = .345
; only_retract_when_crossing_perimeters = 1
; output_filename_format = [input_filename_base]_[timestamp].gcode
; perimeter_acceleration = 25
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_speed = 130
; perimeters = 1
; post_process = 
; print_center = 100,100
; randomize_start = 
; retract_before_travel = 3
; retract_length = 1
; retract_length_toolchange = 0
; retract_lift = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 3
; retract_speed = 26
; rotate = 0
; scale = 1
; skirt_distance = 6
; skirt_height = 0
; skirts = 4
; slowdown_below_layer_time = 4
; small_perimeter_speed = 90%
; solid_fill_pattern = rectilinear
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_speed = 130
; start_gcode = G90 ; use absolute coordinates\nG21 ; set units to millimeters\nM82 ; use absolute distances for extrusion\nG28 ; go home and zero the axes\nG92 X0 Y0 Z0 E0.0\nG1 Z1.0 F240 ; Head on up to a location I can be seen.\nG1 E5 ; let's spew a little.\nG92 E2.0\nG1 E0.0 ; retract a little so I stop drooling.\nG1 X0 Y0 Z0 F3000\nG1 Y30\nG1 X30 \nG1 Y0 \nG1 X100 Y0 Z1.0\nG1 X100 Y30 Z0 E3\nG92 E0\nM106
; support_material = 
; support_material_angle = 45
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_pattern = honeycomb
; support_material_spacing = 4
; support_material_threshold = 48
; temperature = 0,0,0
; threads = 4
; top_solid_infill_speed = 90%
; top_solid_layers = 0
; travel_speed = 300
; use_relative_e_distances = 0
; vibration_limit = 25
; z_offset = 0.28
